; Generated by restunts-export.py (Ghidra)
.8086
.model medium

include seg038.inc

seg038 segment byte public use16 'STUNTSD'
    assume cs:seg038, es:nothing, ss:nothing, ds:dseg

plan_memres          db 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
                     db 0x00, 0x00, 0x00, 0x00, 0x00, 0x20, 0x00, 0x00
                     db 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
                     db 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
                     db 0x00, 0x00
                     db 0
                     db 0
                     db 0
                     db 0
                     db 0
                     db 0
                     db 0
                     db 0
                     db 0
                     db 0
                     db 0
                     db 0
                     db 0
                     db 0
seg038 ends
end
