; Generated by restunts-export.py (Ghidra)
.8086
.model medium

include seg035.inc

seg035 segment byte public use16 'STUNTSC'
    assume cs:seg035, es:nothing, ss:nothing, ds:dseg

    db 0x90

; void * __cdecl16far file_load_shape2d_res_fatal(char * filename)
file_load_shape2d_res_fatal_asm_ proc far
    filename   = word ptr    6

    push    bp
    mov     bp, sp
    mov     ax, 0x1
    push    ax
    push    word ptr [bp+filename]
    push    cs
    call    near ptr file_load_shape2d_res
    add     sp, 0x4
    pop     bp
    retf
file_load_shape2d_res_fatal_asm_ endp
    db 0x90

; void * __cdecl16far file_load_shape2d_res_nofatal(char * filename)
file_load_shape2d_res_nofatal_asm_ proc far
    filename   = word ptr    6

    push    bp
    mov     bp, sp
    sub     ax, ax
    push    ax
    push    word ptr [bp+filename]
    push    cs
    call    near ptr file_load_shape2d_res
    add     sp, 0x4
    pop     bp
    retf
file_load_shape2d_res_nofatal_asm_ endp

; void * __cdecl16far file_load_shape2d_res(char * filename, int is_fatal)
file_load_shape2d_res_asm_ proc far
    local_c    = word ptr  -10
    local_a    = word ptr   -8
    local_8    = word ptr   -6
    local_6    = word ptr   -4
    local_4    = word ptr   -2
    filename   = word ptr    6
    is_fatal   = word ptr    8

    push    bp
    mov     bp, sp
    sub     sp, 0xa
    push    word ptr [bp+filename]
    call    far ptr mmgr_path_to_name
    add     sp, 0x2
    push    ax
    call    far ptr mmgr_get_chunk_by_name
    add     sp, 0x2
    mov     word ptr [bp+local_a], ax
    mov     word ptr [bp+local_8], dx
    or      ax, dx
    jz      LAB_3acd_005a
    mov     ax, word ptr [bp+local_a]
    mov     sp, bp
    pop     bp
    retf
    db 0x90
LAB_3acd_005a:
    push    word ptr [bp+is_fatal]
    push    word ptr [bp+filename]
    call    far ptr file_load_shape2d
    add     sp, 0x4
    mov     word ptr [bp+local_6], ax
    mov     word ptr [bp+local_4], dx
    or      ax, dx
    jnz     LAB_3acd_007a
    mov     ax, word ptr [bp+local_6]
    mov     sp, bp
    pop     bp
    retf
    db 0x90
LAB_3acd_007a:
    push    word ptr [bp+local_4]
    push    word ptr [bp+local_6]
    call    far ptr mmgr_get_chunk_size
    add     sp, 0x4
    mov     word ptr [bp+local_c], ax
    push    ax
    push    word ptr [bp+filename]
    call    far ptr mmgr_alloc_pages
    add     sp, 0x4
    mov     word ptr [bp+local_a], ax
    mov     word ptr [bp+local_8], dx
    push    dx
    push    ax
    push    word ptr [bp+local_4]
    push    word ptr [bp+local_6]
    push    cs
    call    near ptr parse_shape2d
    add     sp, 0x8
    push    word ptr [bp+local_4]
    push    word ptr [bp+local_6]
    call    far ptr mmgr_release
    add     sp, 0x4
    push    word ptr [bp+local_8]
    push    word ptr [bp+local_a]
    call    far ptr mmgr_op_unk
    add     sp, 0x4
    mov     sp, bp
    pop     bp
    retf
file_load_shape2d_res_asm_ endp

; void __cdecl16far parse_shape2d(void * memchunk_, void * mempages)
parse_shape2d_asm_ proc far
    local_3a   = dword ptr -56
    local_36   = word ptr  -52
    local_34   = word ptr  -50
    local_32   = word ptr  -48
    local_30   = dword ptr -46
    local_2c   = word ptr  -42
    local_2a   = word ptr  -40
    local_28   = word ptr  -38
    local_26   = word ptr  -36
    local_20   = word ptr  -30
    local_1e   = dword ptr -28
    local_1a   = dword ptr -24
    local_16   = word ptr  -20
    local_14   = word ptr  -18
    local_12   = word ptr  -16
    local_10   = word ptr  -14
    local_e    = dword ptr -12
    local_a    = dword ptr  -8
    local_6    = dword ptr  -4
    memchunk_  = dword ptr   6
    mempages   = dword ptr  10

    push    bp
    mov     bp, sp
    sub     sp, 0x38
    push    di
    push    si
    push    word ptr [bp+memchunk_+2]
    push    word ptr [bp+memchunk_]
    call    far ptr file_get_res_shape_count
    add     sp, 0x4
    mov     word ptr [bp+local_2a], ax
    shl     ax, 0x1
    shl     ax, 0x1
    add     ax, word ptr [bp+mempages]
    mov     dx, word ptr [bp+mempages+2]
    add     ax, 0x6
    mov     word ptr [bp+local_1a], ax
    mov     word ptr [bp+local_1a+2], dx
    mov     ax, word ptr [bp+mempages]
    mov     word ptr [bp+local_1e], ax
    mov     word ptr [bp+local_1e+2], dx
    mov     ax, word ptr [bp+memchunk_]
    mov     dx, word ptr [bp+memchunk_+2]
    mov     word ptr [bp+local_3a], ax
    mov     word ptr [bp+local_3a+2], dx
    mov     word ptr [bp+local_2c], 0x0
    jmp     LAB_3acd_0129
LAB_3acd_0114:
    les     bx, [bp+local_3a]
    inc     word ptr [bp+local_3a]
    mov     al, byte ptr es:[bx]
    les     bx, [bp+local_1e]
    inc     word ptr [bp+local_1e]
    mov     byte ptr es:[bx], al
    inc     word ptr [bp+local_2c]
LAB_3acd_0129:
    mov     ax, word ptr [bp+local_2a]
    shl     ax, 0x1
    shl     ax, 0x1
    add     ax, 0x6
    cmp     ax, word ptr [bp+local_2c]
    jg      LAB_3acd_0114
    mov     ax, word ptr [bp+local_2a]
    mov     cl, 0x3
    shl     ax, cl
    add     ax, word ptr [bp+mempages]
    mov     dx, word ptr [bp+mempages+2]
    add     ax, 0x6
    mov     word ptr [bp+local_a], ax
    mov     word ptr [bp+local_a+2], dx
    mov     word ptr [bp+local_28], ax
    mov     word ptr [bp+local_26], dx
    mov     word ptr [bp+local_2c], 0x0
    jmp     near ptr LAB_3acd_028b
LAB_3acd_015c:
    push    word ptr [bp+local_30+2]
    push    word ptr [bp+local_30]
    push    cs
    call    near ptr parse_shape2d_helper3
    add     sp, 0x4
    mov     word ptr [bp+local_12], ax
    cmp     ax, 0x3
    jg      LAB_3acd_017c
    mov     ax, word ptr [bp+local_20]
    cmp     word ptr [bp+local_10], ax
    jnc     LAB_3acd_017c
    jmp     near ptr LAB_3acd_026f
LAB_3acd_017c:
    cmp     word ptr [bp+local_10], 0x7f
    jg      LAB_3acd_01a4
    cmp     word ptr [bp+local_10], 0x0
    jz      LAB_3acd_01f9
    les     bx, [bp+local_a]
    inc     word ptr [bp+local_a]
    mov     ax, word ptr [bp+local_10]
    neg     ax
    mov     byte ptr es:[bx], al
    mov     ax, word ptr [bp+local_10]
    sub     word ptr [bp+local_20], ax
    mov     word ptr [bp+local_32], 0x0
    jmp     LAB_3acd_01f1
    db 0x90
LAB_3acd_01a4:
    sub     word ptr [bp+local_10], 0x7f
    sub     word ptr [bp+local_20], 0x7f
    les     bx, [bp+local_a]
    inc     word ptr [bp+local_a]
    mov     byte ptr es:[bx], 0x81
    mov     word ptr [bp+local_32], 0x0
    jmp     LAB_3acd_01c1
    db 0x90
LAB_3acd_01be:
    inc     word ptr [bp+local_32]
LAB_3acd_01c1:
    cmp     word ptr [bp+local_32], 0x7f
    jge     LAB_3acd_017c
    les     bx, [bp+local_6]
    inc     word ptr [bp+local_6]
    mov     al, byte ptr es:[bx]
    les     bx, [bp+local_a]
    inc     word ptr [bp+local_a]
    mov     byte ptr es:[bx], al
    jmp     LAB_3acd_01be
    db 0x90
LAB_3acd_01dc:
    les     bx, [bp+local_6]
    inc     word ptr [bp+local_6]
    mov     al, byte ptr es:[bx]
    les     bx, [bp+local_a]
    inc     word ptr [bp+local_a]
    mov     byte ptr es:[bx], al
    inc     word ptr [bp+local_32]
LAB_3acd_01f1:
    mov     ax, word ptr [bp+local_10]
    cmp     word ptr [bp+local_32], ax
    jl      LAB_3acd_01dc
LAB_3acd_01f9:
    mov     ax, word ptr [bp+local_20]
    cmp     word ptr [bp+local_12], ax
    jbe     LAB_3acd_022b
    mov     word ptr [bp+local_12], ax
    jmp     LAB_3acd_022b
LAB_3acd_0206:
    sub     word ptr [bp+local_12], 0x7f
    sub     word ptr [bp+local_20], 0x7f
    les     bx, [bp+local_a]
    inc     word ptr [bp+local_a]
    mov     byte ptr es:[bx], 0x7f
    les     bx, [bp+local_30]
    mov     al, byte ptr es:[bx]
    les     bx, [bp+local_a]
    inc     word ptr [bp+local_a]
    mov     byte ptr es:[bx], al
    add     word ptr [bp+local_30], 0x7f
LAB_3acd_022b:
    cmp     word ptr [bp+local_12], 0x7f
    jg      LAB_3acd_0206
    cmp     word ptr [bp+local_12], 0x3
    jle     LAB_3acd_025e
    les     bx, [bp+local_a]
    inc     word ptr [bp+local_a]
    mov     al, byte ptr [bp+local_12]
    mov     byte ptr es:[bx], al
    mov     ax, word ptr [bp+local_12]
    sub     word ptr [bp+local_20], ax
    les     bx, [bp+local_30]
    mov     al, byte ptr es:[bx]
    les     bx, [bp+local_a]
    inc     word ptr [bp+local_a]
    mov     byte ptr es:[bx], al
    mov     ax, word ptr [bp+local_12]
    add     word ptr [bp+local_30], ax
LAB_3acd_025e:
    mov     ax, word ptr [bp+local_30]
    mov     dx, word ptr [bp+local_30+2]
    mov     word ptr [bp+local_6], ax
    mov     word ptr [bp+local_6+2], dx
    mov     word ptr [bp+local_10], 0x0
LAB_3acd_026f:
    inc     word ptr [bp+local_30]
    inc     word ptr [bp+local_10]
LAB_3acd_0275:
    cmp     word ptr [bp+local_20], 0x0
    jz      LAB_3acd_027e
    jmp     near ptr LAB_3acd_015c
LAB_3acd_027e:
    les     bx, [bp+local_a]
    inc     word ptr [bp+local_a]
    mov     byte ptr es:[bx], 0x0
    inc     word ptr [bp+local_2c]
LAB_3acd_028b:
    mov     ax, word ptr [bp+local_2a]
    cmp     word ptr [bp+local_2c], ax
    jl      LAB_3acd_0296
    jmp     near ptr LAB_3acd_0350
LAB_3acd_0296:
    push    word ptr [bp+local_2c]
    push    word ptr [bp+memchunk_+2]
    push    word ptr [bp+memchunk_]
    call    far ptr file_get_shape2d
    add     sp, 0x6
    mov     word ptr [bp+local_e], ax
    mov     word ptr [bp+local_e+2], dx
    push    word ptr [bp+local_a+2]
    push    word ptr [bp+local_a]
    call    far ptr parse_shape2d_helper
    add     sp, 0x4
    mov     word ptr [bp+local_16], ax
    mov     word ptr [bp+local_14], dx
    push    dx
    push    ax
    call    far ptr parse_shape2d_helper2
    add     sp, 0x4
    mov     word ptr [bp+local_a], ax
    mov     word ptr [bp+local_a+2], dx
    push    word ptr [bp+local_26]
    push    word ptr [bp+local_28]
    call    far ptr parse_shape2d_helper
    add     sp, 0x4
    push    word ptr [bp+local_a+2]
    push    word ptr [bp+local_a]
    mov     si, ax
    mov     di, dx
    call    far ptr parse_shape2d_helper
    add     sp, 0x4
    sub     ax, si
    sbb     dx, di
    les     bx, [bp+local_1a]
    add     word ptr [bp+local_1a], 0x4
    mov     word ptr es:[bx], ax
    mov     word ptr es:[bx+0x2], dx
    mov     ax, word ptr [bp+local_e]
    mov     dx, word ptr [bp+local_e+2]
    mov     word ptr [bp+local_30], ax
    mov     word ptr [bp+local_30+2], dx
    mov     word ptr [bp+local_32], 0x0
LAB_3acd_0314:
    les     bx, [bp+local_30]
    inc     word ptr [bp+local_30]
    mov     al, byte ptr es:[bx]
    les     bx, [bp+local_a]
    inc     word ptr [bp+local_a]
    mov     byte ptr es:[bx], al
    inc     word ptr [bp+local_32]
    cmp     word ptr [bp+local_32], 0x10
    jl      LAB_3acd_0314
    mov     ax, word ptr [bp+local_30]
    mov     dx, word ptr [bp+local_30+2]
    mov     word ptr [bp+local_6], ax
    mov     word ptr [bp+local_6+2], dx
    mov     word ptr [bp+local_10], 0x0
    les     bx, [bp+local_e]
    mov     ax, word ptr es:[bx+0x2]
    imul    word ptr es:[bx]
    mov     word ptr [bp+local_20], ax
    jmp     near ptr LAB_3acd_0275
LAB_3acd_0350:
    push    word ptr [bp+mempages+2]
    push    word ptr [bp+mempages]
    call    far ptr parse_shape2d_helper
    add     sp, 0x4
    push    word ptr [bp+local_a+2]
    push    word ptr [bp+local_a]
    mov     si, ax
    mov     di, dx
    call    far ptr parse_shape2d_helper
    add     sp, 0x4
    sub     ax, si
    sbb     dx, di
    mov     word ptr [bp+local_36], ax
    mov     word ptr [bp+local_34], dx
    test    byte ptr [bp+local_36], 0xf
    jz      LAB_3acd_0398
    mov     cl, 0x4
LAB_3acd_0382:
    sar     dx, 0x1
    rcr     ax, 0x1
    dec     cl
    jnz     LAB_3acd_0382
    add     ax, 0x1
    adc     dx, 0x0
    mov     word ptr [bp+local_36], ax
    mov     word ptr [bp+local_34], dx
    jmp     LAB_3acd_03a4
LAB_3acd_0398:
    mov     al, 0x4
    push    ax
    lea     ax, [bp+local_36]
    push    ax
    call    far ptr unknown_libname_4
LAB_3acd_03a4:
    push    word ptr [bp+local_36]
    push    word ptr [bp+mempages+2]
    push    word ptr [bp+mempages]
    call    far ptr mmgr_resize_memory
    add     sp, 0x6
    pop     si
    pop     di
    mov     sp, bp
    pop     bp
    retf
parse_shape2d_asm_ endp
    db 0x90

; word __cdecl16far parse_shape2d_helper3(char * param_1)
parse_shape2d_helper3_asm_ proc far
    var_4      = byte ptr   -4
    var_2      = word ptr   -2
    param_1    = dword ptr   6

    push    bp
    mov     bp, sp
    sub     sp, 0x4
    les     bx, [bp+param_1]
    mov     al, byte ptr es:[bx]
    mov     byte ptr [bp+var_4], al
    mov     word ptr [bp+var_2], 0x0
    jmp     LAB_3acd_03d5
LAB_3acd_03d2:
    inc     word ptr [bp+var_2]
LAB_3acd_03d5:
    les     bx, [bp+param_1]
    inc     word ptr [bp+param_1]
    mov     al, byte ptr [bp+var_4]
    cmp     byte ptr es:[bx], al
    jz      LAB_3acd_03d2
    mov     ax, word ptr [bp+var_2]
    mov     sp, bp
    pop     bp
    retf
parse_shape2d_helper3_asm_ endp

seg035 ends
end
