; Generated by restunts-export.py (Ghidra)
.8086
.model medium

include seg013.inc

seg013 segment byte public use16 'STUNTSC'
    assume cs:seg013, es:nothing, ss:nothing, ds:dseg

; void __cdecl16far sprite_1_unk4(int x1_, int y1_, int x2_, int y2_, uint colour)
sprite_1_unk4_asm_ proc far
    var_4      = word ptr   -4
    var_2      = word ptr   -2
    x1_        = word ptr    6
    y1_        = word ptr    8
    x2_        = word ptr   10
    y2_        = word ptr   12
    colour     = word ptr   14

    push    bp
    mov     bp, sp
    sub     sp, 0x4
    mov     ax, word ptr [bp+x2_]
    sub     ax, word ptr [bp+x1_]
    inc     ax
    mov     word ptr [bp+var_2], ax
    mov     ax, word ptr [bp+y2_]
    sub     ax, word ptr [bp+y1_]
    mov     word ptr [bp+var_4], ax
    cmp     word ptr [bp+var_2], 0x0
    jle     LAB_361b_005b
    push    word ptr [bp+colour]
    mov     ax, 0x1
    push    ax
    push    word ptr [bp+var_2]
    push    word ptr [bp+y1_]
    push    word ptr [bp+x1_]
    call    far ptr sprite_1_unk2
    add     sp, 0xa
    push    word ptr [bp+colour]
    mov     ax, 0x1
    push    ax
    push    word ptr [bp+var_2]
    push    word ptr [bp+y2_]
    push    word ptr [bp+x1_]
    call    far ptr sprite_1_unk2
    add     sp, 0xa
LAB_361b_005b:
    cmp     word ptr [bp+var_4], 0x0
    jle     LAB_361b_0091
    push    word ptr [bp+colour]
    push    word ptr [bp+var_4]
    mov     ax, 0x1
    push    ax
    push    word ptr [bp+y1_]
    push    word ptr [bp+x1_]
    call    far ptr sprite_1_unk2
    add     sp, 0xa
    push    word ptr [bp+colour]
    push    word ptr [bp+var_4]
    mov     ax, 0x1
    push    ax
    push    word ptr [bp+y1_]
    push    word ptr [bp+x2_]
    call    far ptr sprite_1_unk2
    add     sp, 0xa
LAB_361b_0091:
    mov     sp, bp
    pop     bp
    retf
sprite_1_unk4_asm_ endp

seg013 ends
end
