; Generated by restunts-export.py (Ghidra)
.8086
.model medium

include seg034.inc

seg034 segment byte public use16 'STUNTSC'
    assume cs:seg034, es:nothing, ss:nothing, ds:dseg

    db 0x90

; void * __cdecl16far file_load_shape2d_fatal(char * filename)
file_load_shape2d_fatal_asm_ proc far
    filename   = word ptr    6

    push    bp
    mov     bp, sp
    mov     ax, 0x1
    push    ax
    push    word ptr [bp+filename]
    push    cs
    call    near ptr file_load_shape2d
    add     sp, 0x4
    pop     bp
    retf
file_load_shape2d_fatal_asm_ endp
    db 0x90

; void * __cdecl16far file_load_shape2d_nofatal(char * filename)
file_load_shape2d_nofatal_asm_ proc far
    filename   = word ptr    6

    push    bp
    mov     bp, sp
    sub     ax, ax
    push    ax
    push    word ptr [bp+filename]
    push    cs
    call    near ptr file_load_shape2d
    add     sp, 0x4
    pop     bp
    retf
file_load_shape2d_nofatal_asm_ endp

; void * __cdecl16far file_load_shape2d(char * filename, int is_fatal)
file_load_shape2d_asm_ proc far
    local_82   = byte ptr  -128
    local_80   = word ptr  -126
    local_7e   = byte ptr  -124
    local_1a   = word ptr  -24
    local_18   = word ptr  -22
    local_16   = word ptr  -20
    local_14   = word ptr  -18
    local_12   = dword ptr -16
    local_e    = word ptr  -12
    local_c    = byte ptr  -10
    local_6    = word ptr   -4
    local_4    = word ptr   -2
    filename   = word ptr    6
    is_fatal   = word ptr    8

    push    bp
    mov     bp, sp
    sub     sp, 0x80
    push    si
    push    word ptr [bp+filename]
    lea     ax, [bp+local_7e]
    push    ax                                 ; char *
    call    far ptr _strcpy
    add     sp, 0x4
    lea     ax, [bp+local_7e]
    mov     word ptr [bp+local_e], ax
    jmp     LAB_3a9d_0055
    db 0x90
LAB_3a9d_004c:
    cmp     byte ptr [bp+local_82], 0x2e
    jz      LAB_3a9d_0061
    inc     word ptr [bp+local_e]
LAB_3a9d_0055:
    mov     bx, word ptr [bp+local_e]
    mov     al, byte ptr [bx]
    mov     byte ptr [bp+local_82], al
    or      al, al
    jnz     LAB_3a9d_004c
LAB_3a9d_0061:
    mov     bx, word ptr [bp+local_e]
    cmp     byte ptr [bx], 0x0
    jnz     LAB_3a9d_00c2
    mov     word ptr [bp+local_16], 0x0
    jmp     LAB_3a9d_0083
LAB_3a9d_0070:
    lea     ax, [bp+local_7e]
    push    ax
    call    far ptr file_find
    add     sp, 0x2
    or      ax, ax
    jnz     _try_load_pvs
    inc     word ptr [bp+local_16]
LAB_3a9d_0083:
    mov     bx, word ptr [bp+local_16]
    shl     bx, 0x1
    mov     si, word ptr [bx+shapeexts]
    cmp     byte ptr [si], 0x0
    jz      _try_load_pvs
    mov     ax, word ptr [bp+local_e]
    mov     word ptr [bp+local_14], ax
    push    si
    push    ax                                 ; char *
    call    far ptr _strcpy
    add     sp, 0x4
    lea     ax, [bp+local_7e]
    push    ax
    call    far ptr mmgr_get_chunk_by_name
    add     sp, 0x2
    mov     word ptr [bp+local_6], ax
    mov     word ptr [bp+local_4], dx
    or      dx, ax
    jz      LAB_3a9d_0070
_end_load_2dshape:
    mov     ax, word ptr [bp+local_6]
    mov     dx, word ptr [bp+local_4]
    pop     si
    mov     sp, bp
    pop     bp
    retf
LAB_3a9d_00c2:
    lea     ax, [bp+local_7e]
    push    ax
    call    far ptr mmgr_get_chunk_by_name
    add     sp, 0x2
    mov     word ptr [bp+local_6], ax
    mov     word ptr [bp+local_4], dx
    or      dx, ax
    jnz     _end_load_2dshape
_try_load_pvs:
    push    word ptr [bp+local_e]
    lea     ax, [bp+local_c]
    push    ax                                 ; char *
    call    far ptr _strcpy
    add     sp, 0x4
    mov     ax, offset a_pvs
    push    ax
    lea     ax, [bp+local_c]
    push    ax                                 ; char *
    call    far ptr _stricmp
    add     sp, 0x4
    or      ax, ax
    jnz     _try_load_xvs
    push    word ptr [bp+is_fatal]
    lea     ax, [bp+local_7e]
    push    ax
    call    far ptr file_decomp
    add     sp, 0x4
    mov     word ptr [bp+local_6], ax
    mov     word ptr [bp+local_4], dx
    or      ax, dx
    jz      _end_load_2dshape
    push    dx
    push    word ptr [bp+local_6]
    call    far ptr file_get_unflip_size
    add     sp, 0x4
    push    ax
    mov     ax, offset aUnflip_0
    push    ax
    call    far ptr mmgr_alloc_pages
    add     sp, 0x4
    mov     word ptr [bp+local_12], ax
    mov     word ptr [bp+local_12+2], dx
    push    dx
    push    ax
    push    word ptr [bp+local_4]
    push    word ptr [bp+local_6]
    call    far ptr file_unflip_shape2d
    add     sp, 0x8
    push    word ptr [bp+local_12+2]
    push    word ptr [bp+local_12]
    call    far ptr mmgr_release
    add     sp, 0x4
    jmp     near ptr _end_load_2dshape
_try_load_xvs:
    mov     ax, offset a_xvs
    push    ax
    lea     ax, [bp+local_c]
    push    ax                                 ; char *
    call    far ptr _stricmp
    add     sp, 0x4
    or      ax, ax
    jnz     _try_load_pes
    push    word ptr [bp+is_fatal]
    lea     ax, [bp+local_7e]
    push    ax
    call    far ptr file_decomp
_do_end_load_2dshape:
    add     sp, 0x4
    mov     word ptr [bp+local_6], ax
    mov     word ptr [bp+local_4], dx
    jmp     near ptr _end_load_2dshape
_try_load_pes:
    mov     ax, offset a_pes
    push    ax
    lea     ax, [bp+local_c]
    push    ax                                 ; char *
    call    far ptr _stricmp
    add     sp, 0x4
    or      ax, ax
    jz      LAB_3a9d_0197
    jmp     near ptr _try_load_esh
LAB_3a9d_0197:
    push    word ptr [bp+is_fatal]
    lea     ax, [bp+local_7e]
    push    ax
    call    far ptr file_decomp
    add     sp, 0x4
    mov     word ptr [bp+local_6], ax
    mov     word ptr [bp+local_4], dx
    or      ax, dx
    jnz     LAB_3a9d_01b3
    jmp     near ptr _end_load_2dshape
LAB_3a9d_01b3:
    mov     ax, 0x3e8
    push    ax
    mov     ax, offset aUnflip
    push    ax
    call    far ptr mmgr_alloc_pages
    add     sp, 0x4
    mov     word ptr [bp+local_12], ax
    mov     word ptr [bp+local_12+2], dx
    push    dx
    push    ax
    push    word ptr [bp+local_4]
    push    word ptr [bp+local_6]
    call    far ptr file_unflip_shape2d_pes
    add     sp, 0x8
    push    word ptr [bp+local_12+2]
    push    word ptr [bp+local_12]
    call    far ptr mmgr_release
    add     sp, 0x4
LAB_3a9d_01e7:
    push    word ptr [bp+local_4]
    push    word ptr [bp+local_6]
    call    far ptr file_load_shape2d_expandedsize
    add     sp, 0x4
    mov     word ptr [bp+local_80], ax
    mov     ax, offset aMga
    push    ax
    push    word ptr [bp+local_4]
    push    word ptr [bp+local_6]
    call    far ptr locate_shape_nofatal
    add     sp, 0x6
    mov     word ptr [bp+local_1a], ax
    mov     word ptr [bp+local_18], dx
    or      ax, dx
    jz      LAB_3a9d_0223
    mov     ax, word ptr [bp+local_1a]
    add     ax, 0x10
    push    dx
    push    ax
    push    cs
    call    near ptr file_load_shape2d_palmap_init
    add     sp, 0x4
LAB_3a9d_0223:
    push    word ptr [bp+local_80]
    lea     ax, [bp+local_7e]
    push    ax
    call    far ptr mmgr_alloc_pages
    add     sp, 0x4
    mov     word ptr [bp+local_12], ax
    mov     word ptr [bp+local_12+2], dx
    les     bx, [bp+local_12]
    mov     ax, word ptr [bp+local_80]
    sub     dx, dx
    mov     cl, 0x4
LAB_3a9d_0242:
    shl     ax, 0x1
    rcl     dx, 0x1
    dec     cl
    jz      LAB_3a9d_0290
    jmp     LAB_3a9d_0242
_try_load_esh:
    mov     ax, offset a_esh
    push    ax
    lea     ax, [bp+local_c]
    push    ax                                 ; char *
    call    far ptr _stricmp
    add     sp, 0x4
    or      ax, ax
    jnz     LAB_3a9d_0280
    push    word ptr [bp+is_fatal]
    lea     ax, [bp+local_7e]
    push    ax
    call    far ptr file_load_binary
    add     sp, 0x4
    mov     word ptr [bp+local_6], ax
    mov     word ptr [bp+local_4], dx
    or      ax, dx
    jz      LAB_3a9d_027c
    jmp     near ptr LAB_3a9d_01e7
LAB_3a9d_027c:
    jmp     near ptr _end_load_2dshape
    db 0x90
LAB_3a9d_0280:
    push    word ptr [bp+is_fatal]
    lea     ax, [bp+local_7e]
    push    ax
    call    far ptr file_load_binary
    jmp     near ptr _do_end_load_2dshape
    db 0x90
LAB_3a9d_0290:
    mov     word ptr es:[bx], ax
    mov     word ptr es:[bx+0x2], dx
    push    word ptr [bp+local_12+2]
    push    word ptr [bp+local_12]
    push    word ptr [bp+local_4]
    push    word ptr [bp+local_6]
    call    far ptr file_load_shape2d_expand
    add     sp, 0x8
    push    word ptr [bp+local_4]
    push    word ptr [bp+local_6]
    call    far ptr mmgr_release
    add     sp, 0x4
    push    word ptr [bp+local_12+2]
    push    word ptr [bp+local_12]
    call    far ptr mmgr_op_unk
    add     sp, 0x4
    mov     word ptr [bp+local_6], ax
    mov     word ptr [bp+local_4], dx
    mov     ax, offset palmap
    push    ax
    push    dx
    push    word ptr [bp+local_6]
    call    far ptr file_load_shape2d_palmap_apply
    add     sp, 0x6
    jmp     near ptr _end_load_2dshape
file_load_shape2d_asm_ endp

; void __cdecl16far file_load_shape2d_palmap_init(char * pal)
file_load_shape2d_palmap_init_asm_ proc far
    var_2      = word ptr   -2
    pal        = dword ptr   6

    push    bp
    mov     bp, sp
    sub     sp, 0x2
    push    si
    mov     word ptr [bp+var_2], 0x0
LAB_3a9d_02ec:
    mov     bx, word ptr [bp+var_2]
    les     si, [bp+pal]
    mov     al, byte ptr es:[bx+si]
    mov     byte ptr [bx+0x5472], al
    inc     word ptr [bp+var_2]
    cmp     word ptr [bp+var_2], 0x10
    jl      LAB_3a9d_02ec
    pop     si
    mov     sp, bp
    pop     bp
    retf
file_load_shape2d_palmap_init_asm_ endp

seg034 ends
end
