; Generated by restunts-export.py (Ghidra)
.8086
.model medium

include seg025.inc

seg025 segment byte public use16 'STUNTSC'
    assume cs:seg025, es:nothing, ss:nothing, ds:dseg

    db 0x90

; void __cdecl16far sub_3702E(int param_1, int param_2, int param_3, int param_4, byte param_5)
sub_3702E_asm_ proc far
    var_4      = word ptr   -4
    var_2      = word ptr   -2
    param_1    = word ptr    6
    param_2    = word ptr    8
    param_3    = word ptr   10
    param_4    = word ptr   12
    param_5    = byte ptr   14

    push    bp
    mov     bp, sp
    sub     sp, 0x4
    push    si
    mov     ax, word ptr [bp+param_3]
    sub     ax, word ptr [bp+param_1]
    inc     ax
    mov     word ptr [bp+var_2], ax
    mov     ax, word ptr [bp+param_4]
    sub     ax, word ptr [bp+param_2]
    dec     ax
    mov     word ptr [bp+var_4], ax
    cmp     word ptr [bp+var_2], 0x0
    jle     LAB_3702_005f
    push    word ptr [bp+param_5]
    mov     ax, 0x1
    push    ax
    push    word ptr [bp+var_2]
    push    word ptr [bp+param_2]
    push    word ptr [bp+param_1]
    call    far ptr sub_35B76
    add     sp, 0xa
    push    word ptr [bp+param_5]
    mov     ax, 0x1
    push    ax
    push    word ptr [bp+var_2]
    push    word ptr [bp+param_4]
    push    word ptr [bp+param_1]
    call    far ptr sub_35B76
    add     sp, 0xa
LAB_3702_005f:
    cmp     word ptr [bp+var_4], 0x0
    jle     LAB_3702_0095
    mov     si, word ptr [bp+param_2]
    inc     si
    push    word ptr [bp+param_5]
    push    word ptr [bp+var_4]
    mov     ax, 0x1
    push    ax
    push    si
    push    word ptr [bp+param_1]
    call    far ptr sub_35B76
    add     sp, 0xa
    push    word ptr [bp+param_5]
    push    word ptr [bp+var_4]
    mov     ax, 0x1
    push    ax
    push    si
    push    word ptr [bp+param_3]
    call    far ptr sub_35B76
    add     sp, 0xa
LAB_3702_0095:
    pop     si
    mov     sp, bp
    pop     bp
    retf
sub_3702E_asm_ endp

seg025 ends
end
