; Generated by restunts-export.py (Ghidra)
.8086
.model medium

include custom.inc
include structs.inc
include seg000.inc
include seg001.inc
include seg002.inc
include seg003.inc
include seg004.inc
include seg005.inc
include seg006.inc
include seg007.inc
include seg008.inc
include seg009.inc
include seg010.inc
include seg011.inc
include seg012.inc
include seg013.inc
include seg014.inc
include seg015.inc
include seg016.inc
include seg017.inc
include seg018.inc
include seg019.inc
include seg020.inc
include seg021.inc
include seg022.inc
include seg023.inc
include seg024.inc
include seg025.inc
include seg026.inc
include seg027.inc
include seg028.inc
include seg029.inc
include seg030.inc
include seg031.inc
include seg032.inc
include seg033.inc
include seg034.inc
include seg035.inc
include seg036.inc
include seg038.inc
include seg039.inc
include dseg.inc
include dsegu.inc

seg037 segment byte public use16 'STUNTSC'
    assume cs:seg037, es:nothing, ss:nothing, ds:dseg

    public file_load_shape2d_expandedsize

; uint __cdecl16far file_load_shape2d_expandedsize(void * memchunk_)
file_load_shape2d_expandedsize proc far
    var_sizelo = word ptr  -14
    var_sizehi = word ptr  -12
    var_shapecount = word ptr  -10
    var_counter = word ptr   -8
    var_6      = word ptr   -6
    var_memshape = dword ptr  -4
    memchunk_  = dword ptr   6

    push    bp
    mov     bp, sp
    sub     sp, 0xe
    push    word ptr [bp+memchunk_+2]
    push    word ptr [bp+memchunk_]
    call    far ptr file_get_res_shape_count
    add     sp, 0x4
    mov     word ptr [bp+var_shapecount], ax
    mov     cl, 0x3
    shl     ax, cl
    add     ax, 0x10
    cwd
    mov     word ptr [bp+var_sizelo], ax
    mov     word ptr [bp+var_sizehi], dx
    mov     word ptr [bp+var_counter], 0x0
    jmp     LAB_3b12_0071
LAB_3b12_0036:
    push    word ptr [bp+var_counter]
    push    word ptr [bp+memchunk_+2]
    push    word ptr [bp+memchunk_]
    call    far ptr file_get_shape2d
    add     sp, 0x6
    mov     word ptr [bp+var_memshape], ax
    mov     word ptr [bp+var_memshape+2], dx
    les     bx, [bp+var_memshape]
    mov     ax, word ptr es:[bx+0x2]
    imul    word ptr es:[bx]
    mov     cl, 0x3
    shl     ax, cl
    mov     word ptr [bp+var_6], ax
    sub     dx, dx
    add     word ptr [bp+var_sizelo], ax
    adc     word ptr [bp+var_sizehi], dx
    add     word ptr [bp+var_sizelo], 0x10
    adc     word ptr [bp+var_sizehi], 0x0
    inc     word ptr [bp+var_counter]
LAB_3b12_0071:
    mov     ax, word ptr [bp+var_shapecount]
    cmp     word ptr [bp+var_counter], ax
    jl      LAB_3b12_0036
    add     word ptr [bp+var_sizelo], 0x10
    adc     word ptr [bp+var_sizehi], 0x0
    mov     al, 0x4
    push    ax
    lea     ax, [bp+var_sizelo]
    push    ax
    call    far ptr unknown_libname_4
    mov     ax, word ptr [bp+var_sizelo]
    mov     sp, bp
    pop     bp
    retf
file_load_shape2d_expandedsize endp
    db 0
    db 0
    db 0
    db 0
    db 0
    db 0
    db 0
    db 0
    db 0
    db 0
    db 0
    db 0
seg037 ends
end
