; Generated by restunts-export.py (Ghidra)
.8086
.model medium

include custom.inc
include structs.inc
include seg000.inc
include seg001.inc
include seg002.inc
include seg003.inc
include seg004.inc
include seg005.inc
include seg006.inc
include seg007.inc
include seg008.inc
include seg009.inc
include seg010.inc
include seg011.inc
include seg012.inc
include seg013.inc
include seg014.inc
include seg015.inc
include seg016.inc
include seg017.inc
include seg019.inc
include seg020.inc
include seg021.inc
include seg022.inc
include seg023.inc
include seg024.inc
include seg025.inc
include seg026.inc
include seg027.inc
include seg028.inc
include seg029.inc
include seg030.inc
include seg031.inc
include seg032.inc
include seg033.inc
include seg034.inc
include seg035.inc
include seg036.inc
include seg037.inc
include seg038.inc
include seg039.inc
include dseg.inc
include dsegu.inc

seg018 segment byte public use16 'STUNTSC'
    assume cs:seg018, es:nothing, ss:nothing, ds:dseg

    public kb_shift_checking1
    public kb_shift_checking2

    retf
    db 0x90

; void __cdecl16far kb_shift_checking1(void)
kb_shift_checking1 proc far
    mov     ax, 0x40
    mov     es, ax
    or      byte ptr es:[0x17], 0x20           ; 40h:17h = keyboard shift flags
    call    far ptr kb_checking
    retf
kb_shift_checking1 endp

; void __cdecl16far kb_shift_checking2(void)
kb_shift_checking2 proc far
    mov     ax, 0x40
    mov     es, ax
    and     byte ptr es:[0x17], 0xdf           ; 40h:17h = keyboard shift flags
    call    far ptr kb_checking
    retf
kb_shift_checking2 endp

seg018 ends
end
