; Generated by restunts-export.py (Ghidra)
.8086
.model medium

include seg021.inc

seg021 segment byte public use16 'STUNTSC'
    assume cs:seg021, es:nothing, ss:nothing, ds:dseg

; void __cdecl16far heapsort_by_order(int n, int * heap, int * data)
heapsort_by_order_asm_ proc far
    var_index  = word ptr   -8
    var_counter = word ptr   -6
    var_halfindex = word ptr   -4
    var_value  = word ptr   -2
    n          = word ptr    6
    heap       = word ptr    8
    data       = word ptr   10

    push    bp
    mov     bp, sp
    sub     sp, 0x8
    push    di
    push    si
    mov     ax, word ptr [bp+n]
    cwd
    sub     ax, dx
    sar     ax, 0x1
    jmp     LAB_36be_008b
LAB_36be_001a:
    mov     si, word ptr [bp+var_index]
    shl     si, 0x1
    mov     bx, word ptr [bp+heap]
    mov     ax, word ptr [bx+si]
    mov     word ptr [bp+var_value], ax
    mov     di, word ptr [bp+var_index]
    add     di, word ptr [bp+var_halfindex]
    shl     di, 0x1
    mov     ax, word ptr [bx+di]
    mov     word ptr [bx+si], ax
    mov     ax, word ptr [bp+var_value]
    mov     word ptr [bx+di], ax
    mov     bx, word ptr [bp+data]
    mov     ax, word ptr [bx+si]
    mov     word ptr [bp+var_value], ax
    mov     ax, word ptr [bx+di]
    mov     word ptr [bx+si], ax
    mov     ax, word ptr [bp+var_value]
    mov     word ptr [bx+di], ax
    mov     ax, word ptr [bp+var_halfindex]
    sub     word ptr [bp+var_index], ax
LAB_36be_004f:
    cmp     word ptr [bp+var_index], 0x0
    jl      LAB_36be_006b
    mov     bx, word ptr [bp+var_index]
    shl     bx, 0x1
    mov     si, word ptr [bp+heap]
    mov     ax, word ptr [bx+si]
    mov     bx, word ptr [bp+var_index]
    add     bx, word ptr [bp+var_halfindex]
    shl     bx, 0x1
    cmp     word ptr [bx+si], ax
    jg      LAB_36be_001a
LAB_36be_006b:
    inc     word ptr [bp+var_counter]
LAB_36be_006e:
    mov     ax, word ptr [bp+n]
    cmp     word ptr [bp+var_counter], ax
    jge     LAB_36be_0082
    mov     ax, word ptr [bp+var_counter]
    sub     ax, word ptr [bp+var_halfindex]
    mov     word ptr [bp+var_index], ax
    jmp     LAB_36be_004f
    db 0x90
LAB_36be_0082:
    mov     cx, 0x2
    mov     ax, word ptr [bp+var_halfindex]
    cwd
    idiv    cx
LAB_36be_008b:
    mov     word ptr [bp+var_halfindex], ax
    or      ax, ax
    jle     LAB_36be_0098
    mov     word ptr [bp+var_counter], ax
    jmp     LAB_36be_006e
    db 0x90
LAB_36be_0098:
    pop     si
    pop     di
    mov     sp, bp
    pop     bp
    retf
heapsort_by_order_asm_ endp

seg021 ends
end
