; Generated by restunts-export.py (Ghidra)
.8086
.model medium

include custom.inc
include structs.inc
include seg000.inc
include seg001.inc
include seg002.inc
include seg003.inc
include seg004.inc
include seg005.inc
include seg006.inc
include seg007.inc
include seg008.inc
include seg009.inc
include seg010.inc
include seg011.inc
include seg012.inc
include seg013.inc
include seg014.inc
include seg015.inc
include seg016.inc
include seg017.inc
include seg018.inc
include seg019.inc
include seg020.inc
include seg021.inc
include seg022.inc
include seg024.inc
include seg025.inc
include seg026.inc
include seg027.inc
include seg028.inc
include seg029.inc
include seg030.inc
include seg031.inc
include seg032.inc
include seg033.inc
include seg034.inc
include seg035.inc
include seg036.inc
include seg037.inc
include seg038.inc
include seg039.inc
include dseg.inc
include dsegu.inc

seg023 segment byte public use16 'STUNTSC'
    assume cs:seg023, es:nothing, ss:nothing, ds:dseg

    public preRender_wheel_helper

; void __cdecl16far preRender_wheel_helper(word * param_1, POINT2D * vertlines, int param_3)
preRender_wheel_helper proc far
    var_A      = word ptr  -10
    var_8      = word ptr   -8
    var_6      = word ptr   -6
    var_4      = word ptr   -4
    var_2      = word ptr   -2
    param_1    = word ptr    6
    vertlines  = word ptr    8
    param_3    = word ptr   10

    push    bp
    mov     bp, sp
    sub     sp, 0xa
    push    si
    push    word ptr [bp+param_3]
    push    word ptr [bp+vertlines]
    push    word ptr [bp+param_1]
    call    far ptr preRender_wheel_helper2
    add     sp, 0x6
    mov     bx, word ptr [bp+param_1]
    mov     ax, word ptr [bx+0xc]
    sub     ax, word ptr [bx]
    mov     word ptr [bp+var_8], ax
    mov     ax, word ptr [bx+0xe]
    sub     ax, word ptr [bx+0x2]
    mov     word ptr [bp+var_A], ax
    mov     ax, word ptr [bp+vertlines]
    mov     word ptr [bp+var_2], ax
    add     ax, 0x80
    mov     word ptr [bp+var_4], ax
    mov     word ptr [bp+var_6], 0x0
LAB_36ec_003d:
    mov     bx, word ptr [bp+var_4]
    mov     si, word ptr [bp+var_2]
    mov     ax, word ptr [si]
    add     ax, word ptr [bp+var_8]
    mov     word ptr [bx], ax
    mov     ax, word ptr [si+0x2]
    add     ax, word ptr [bp+var_A]
    mov     word ptr [bx+0x2], ax
    add     word ptr [bp+var_2], 0x4
    add     word ptr [bp+var_4], 0x4
    inc     word ptr [bp+var_6]
    cmp     word ptr [bp+var_6], 0x10
    jl      LAB_36ec_003d
    pop     si
    mov     sp, bp
    pop     bp
    retf
preRender_wheel_helper endp

seg023 ends
end
