; Generated by restunts-export.py (Ghidra)
.8086
.model medium

include custom.inc
include structs.inc
include seg000.inc
include seg001.inc
include seg002.inc
include seg003.inc
include seg004.inc
include seg005.inc
include seg006.inc
include seg007.inc
include seg008.inc
include seg009.inc
include seg010.inc
include seg011.inc
include seg012.inc
include seg013.inc
include seg014.inc
include seg015.inc
include seg016.inc
include seg017.inc
include seg018.inc
include seg020.inc
include seg021.inc
include seg022.inc
include seg023.inc
include seg024.inc
include seg025.inc
include seg026.inc
include seg027.inc
include seg028.inc
include seg029.inc
include seg030.inc
include seg031.inc
include seg032.inc
include seg033.inc
include seg034.inc
include seg035.inc
include seg036.inc
include seg037.inc
include seg038.inc
include seg039.inc
include dseg.inc
include dsegu.inc

seg019 segment byte public use16 'STUNTSC'
    assume cs:seg019, es:nothing, ss:nothing, ds:dseg

    public preRender_wheel_helper2

; void __cdecl16far preRender_wheel_helper2(word * param_1, POINT2D * vertlines, int param_3)
preRender_wheel_helper2 proc far
    var_C      = word ptr  -12
    var_A      = word ptr  -10
    var_8      = word ptr   -8
    var_6      = word ptr   -6
    var_4      = word ptr   -4
    var_2      = word ptr   -2
    param_1    = word ptr    6
    vertlines  = word ptr    8
    param_3    = word ptr   10

    push    bp
    mov     bp, sp
    sub     sp, 0xc
    push    si
    mov     bx, word ptr [bp+param_1]
    mov     ax, word ptr [bx]
    mov     dx, word ptr [bx+0x2]
    mov     word ptr [bp+var_C], ax
    mov     word ptr [bp+var_A], dx
    mov     si, ax
    push    word ptr [bp+param_3]
    mov     ax, word ptr [bx+0x4]
    sub     ax, si
    push    ax
    call    far ptr multiply_and_scale
    add     sp, 0x4
    add     ax, si
    mov     word ptr [bp+var_8], ax
    push    word ptr [bp+param_3]
    mov     bx, word ptr [bp+param_1]
    mov     ax, word ptr [bx+0x6]
    sub     ax, word ptr [bx+0x2]
    push    ax
    call    far ptr multiply_and_scale
    add     sp, 0x4
    mov     bx, word ptr [bp+param_1]
    mov     cx, word ptr [bx+0x2]
    add     cx, ax
    mov     word ptr [bp+var_6], cx
    push    word ptr [bp+param_3]
    mov     ax, word ptr [bx+0x8]
    sub     ax, si
    push    ax
    call    far ptr multiply_and_scale
    add     sp, 0x4
    add     ax, si
    mov     word ptr [bp+var_4], ax
    push    word ptr [bp+param_3]
    mov     bx, word ptr [bp+param_1]
    mov     ax, word ptr [bx+0xa]
    sub     ax, word ptr [bx+0x2]
    push    ax
    call    far ptr multiply_and_scale
    add     sp, 0x4
    mov     bx, word ptr [bp+param_1]
    mov     cx, word ptr [bx+0x2]
    add     cx, ax
    mov     word ptr [bp+var_2], cx
    push    word ptr [bp+vertlines]
    push    bx
    call    far ptr preRender_wheel_helper3
    add     sp, 0x4
    mov     ax, word ptr [bp+vertlines]
    add     ax, 0x40
    push    ax
    lea     ax, [bp+var_C]
    push    ax
    call    far ptr preRender_wheel_helper3
    add     sp, 0x4
    pop     si
    mov     sp, bp
    pop     bp
    retf
preRender_wheel_helper2 endp

seg019 ends
end
