; Generated by restunts-export.py (Ghidra)
.8086
.model medium

include seg036.inc

seg036 segment byte public use16 'STUNTSC'
    assume cs:seg036, es:nothing, ss:nothing, ds:dseg

; returns size of largest shape (XxY+32) in the shape collection resource  
; ushort __cdecl16far file_get_unflip_size(void * memchunk_)
file_get_unflip_size_asm_ proc far
    var_C      = word ptr  -12
    var_A      = word ptr  -10
    var_8      = word ptr   -8
    var_6      = word ptr   -6
    var_4      = dword ptr  -4
    memchunk_  = dword ptr   6

    push    bp
    mov     bp, sp
    sub     sp, 0xc
    push    word ptr [bp+memchunk_+2]
    push    word ptr [bp+memchunk_]
    call    far ptr file_get_res_shape_count
    add     sp, 0x4
    mov     word ptr [bp+var_A], ax
    mov     word ptr [bp+var_6], 0x0
    mov     word ptr [bp+var_8], 0x0
    jmp     LAB_3b0b_006b
    db 0x90
LAB_3b0b_002e:
    push    word ptr [bp+var_8]
    push    word ptr [bp+memchunk_+2]
    push    word ptr [bp+memchunk_]
    call    far ptr file_get_shape2d
    add     sp, 0x6
    mov     word ptr [bp+var_4], ax
    mov     word ptr [bp+var_4+2], dx
    les     bx, [bp+var_4]
    mov     ax, word ptr es:[bx+0x2]
    imul    word ptr es:[bx]
    add     ax, 0x20
    mov     word ptr [bp+var_C], ax
    mov     cl, 0x4
    shr     word ptr [bp+var_C], cl
    mov     ax, word ptr [bp+var_6]
    cmp     word ptr [bp+var_C], ax
    jbe     LAB_3b0b_0068
    mov     ax, word ptr [bp+var_C]
    mov     word ptr [bp+var_6], ax
LAB_3b0b_0068:
    inc     word ptr [bp+var_8]
LAB_3b0b_006b:
    mov     ax, word ptr [bp+var_A]
    cmp     word ptr [bp+var_8], ax
    jl      LAB_3b0b_002e
    mov     ax, word ptr [bp+var_6]
    mov     sp, bp
    pop     bp
    retf
file_get_unflip_size_asm_ endp

seg036 ends
end
