; Generated by restunts-export.py (Ghidra)
.8086
.model medium

include custom.inc
include structs.inc
include seg000.inc
include seg001.inc
include seg002.inc
include seg003.inc
include seg004.inc
include seg005.inc
include seg006.inc
include seg007.inc
include seg008.inc
include seg009.inc
include seg010.inc
include seg011.inc
include seg012.inc
include seg013.inc
include seg014.inc
include seg015.inc
include seg017.inc
include seg018.inc
include seg019.inc
include seg020.inc
include seg021.inc
include seg022.inc
include seg023.inc
include seg024.inc
include seg025.inc
include seg026.inc
include seg027.inc
include seg028.inc
include seg029.inc
include seg030.inc
include seg031.inc
include seg032.inc
include seg033.inc
include seg034.inc
include seg035.inc
include seg036.inc
include seg037.inc
include seg038.inc
include seg039.inc
include dseg.inc
include dsegu.inc

seg016 segment byte public use16 'STUNTSC'
    assume cs:seg016, es:nothing, ss:nothing, ds:dseg

    public locate_many_resources
    public nopsub_367E4
    public nopsub_36826
    public nopsub_36868

    db 0x90

; void __cdecl16far locate_many_resources(void * data, char * names, void * * result)
locate_many_resources proc far
    data       = dword ptr   6
    names      = word ptr   10
    result     = dword ptr  14

    push    bp
    mov     bp, sp
    jmp     LAB_367b_0029
    db 0x90
LAB_367b_0008:
    push    word ptr [bp+names]
    push    word ptr [bp+data+2]
    push    word ptr [bp+data]
    call    far ptr locate_shape_fatal
    add     sp, 0x6
    mov     bx, word ptr [bp+0xc]
    add     word ptr [bp+0xc], 0x4
    mov     word ptr [bx], ax
    mov     word ptr [bx+0x2], dx
    add     word ptr [bp+names], 0x4
LAB_367b_0029:
    mov     bx, word ptr [bp+names]
    cmp     byte ptr [bx], 0x0
    jnz     LAB_367b_0008
    pop     bp
    retf
locate_many_resources endp
    db 0x90

; undefined __cdecl16far nopsub_367E4(int param_1, int param_2, char * param_3, int param_4)
nopsub_367E4 proc far
    var_2      = word ptr   -2
    param_1    = word ptr    6
    param_2    = word ptr    8
    param_3    = word ptr   10
    param_4    = word ptr   12

    push    bp
    mov     bp, sp
    sub     sp, 0x2
    push    si
    mov     word ptr [bp+var_2], 0x0
    jmp     LAB_367b_0069
LAB_367b_0042:
    push    word ptr [bp+param_3]
    push    word ptr [bp+param_2]
    push    word ptr [bp+param_1]
    call    far ptr locate_shape_nofatal
    add     sp, 0x6
    mov     bx, word ptr [bp+var_2]
    inc     word ptr [bp+var_2]
    shl     bx, 0x1
    shl     bx, 0x1
    mov     si, word ptr [bp+param_4]
    mov     word ptr [bx+si], ax
    mov     word ptr [bx+si+0x2], dx
    add     word ptr [bp+param_3], 0x4
LAB_367b_0069:
    mov     bx, word ptr [bp+param_3]
    cmp     byte ptr [bx], 0x0
    jnz     LAB_367b_0042
    pop     si
    mov     sp, bp
    pop     bp
    retf
nopsub_367E4 endp

; undefined __cdecl16far nopsub_36826(int param_1, undefined2 param_2, char * param_3, int param_4)
nopsub_36826 proc far
    var_2      = word ptr   -2
    param_1    = word ptr    6
    param_2    = word ptr    8
    param_3    = word ptr   10
    param_4    = word ptr   12

    push    bp
    mov     bp, sp
    sub     sp, 0x2
    push    si
    mov     word ptr [bp+var_2], 0x0
    jmp     LAB_367b_00ab
LAB_367b_0084:
    push    word ptr [bp+param_3]
    push    word ptr [bp+param_2]
    push    word ptr [bp+param_1]
    call    far ptr locate_sound_fatal
    add     sp, 0x6
    mov     bx, word ptr [bp+var_2]
    inc     word ptr [bp+var_2]
    shl     bx, 0x1
    shl     bx, 0x1
    mov     si, word ptr [bp+param_4]
    mov     word ptr [bx+si], ax
    mov     word ptr [bx+si+0x2], dx
    add     word ptr [bp+param_3], 0x4
LAB_367b_00ab:
    mov     bx, word ptr [bp+param_3]
    cmp     byte ptr [bx], 0x0
    jnz     LAB_367b_0084
    pop     si
    mov     sp, bp
    pop     bp
    retf
nopsub_36826 endp

; undefined __cdecl16far nopsub_36868(int param_1, int param_2, char * param_3, int param_4)
nopsub_36868 proc far
    var_2      = word ptr   -2
    param_1    = word ptr    6
    param_2    = word ptr    8
    param_3    = word ptr   10
    param_4    = word ptr   12

    push    bp
    mov     bp, sp
    sub     sp, 0x2
    push    si
    mov     word ptr [bp+var_2], 0x0
    jmp     LAB_367b_00ed
LAB_367b_00c6:
    push    word ptr [bp+param_3]
    push    word ptr [bp+param_2]
    push    word ptr [bp+param_1]
    call    far ptr locate_shape_nofatal
    add     sp, 0x6
    mov     bx, word ptr [bp+var_2]
    inc     word ptr [bp+var_2]
    shl     bx, 0x1
    shl     bx, 0x1
    mov     si, word ptr [bp+param_4]
    mov     word ptr [bx+si], ax
    mov     word ptr [bx+si+0x2], dx
    add     word ptr [bp+param_3], 0x4
LAB_367b_00ed:
    mov     bx, word ptr [bp+param_3]
    cmp     byte ptr [bx], 0x0
    jnz     LAB_367b_00c6
    pop     si
    mov     sp, bp
    pop     bp
    retf
nopsub_36868 endp

seg016 ends
end
