; Generated by restunts-export.py (Ghidra)
.8086
.model medium

include seg020.inc

seg020 segment byte public use16 'STUNTSC'
    assume cs:seg020, es:nothing, ss:nothing, ds:dseg

    db 0x90

; void __cdecl16far preRender_sphere_helper(int * param_1, uint colour)
preRender_sphere_helper_asm_ proc far
    vertlines  = dword ptr -128
    param_1    = word ptr    6
    colour     = word ptr    8

    push    bp
    mov     bp, sp
    sub     sp, 0x80
    lea     ax, [bp+vertlines]
    push    ax
    push    word ptr [bp+param_1]
    call    far ptr preRender_sphere_helper2
    add     sp, 0x4
    lea     ax, [bp+vertlines]
    push    ax
    mov     ax, 0x20
    push    ax
    push    word ptr [bp+colour]
    call    far ptr preRender_default_alt
    mov     sp, bp
    pop     bp
    retf
preRender_sphere_helper_asm_ endp

seg020 ends
end
