; Generated by restunts-export.py (Ghidra)
.8086
.model medium

include seg023.inc

seg023 segment byte public use16 'STUNTSC'
    assume cs:seg023, es:nothing, ss:nothing, ds:dseg

; void __cdecl16far preRender_wheel_helper(word * param_1, POINT2D * vertlines, int param_3)
preRender_wheel_helper_asm_ proc far
    var_A      = word ptr  -10
    var_8      = word ptr   -8
    var_6      = word ptr   -6
    var_4      = word ptr   -4
    var_2      = word ptr   -2
    param_1    = word ptr    6
    vertlines  = word ptr    8
    param_3    = word ptr   10

    push    bp
    mov     bp, sp
    sub     sp, 0xa
    push    si
    push    word ptr [bp+param_3]
    push    word ptr [bp+vertlines]
    push    word ptr [bp+param_1]
    call    far ptr preRender_wheel_helper2
    add     sp, 0x6
    mov     bx, word ptr [bp+param_1]
    mov     ax, word ptr [bx+0xc]
    sub     ax, word ptr [bx]
    mov     word ptr [bp+var_8], ax
    mov     ax, word ptr [bx+0xe]
    sub     ax, word ptr [bx+0x2]
    mov     word ptr [bp+var_A], ax
    mov     ax, word ptr [bp+vertlines]
    mov     word ptr [bp+var_2], ax
    add     ax, 0x80
    mov     word ptr [bp+var_4], ax
    mov     word ptr [bp+var_6], 0x0
LAB_36ec_003d:
    mov     bx, word ptr [bp+var_4]
    mov     si, word ptr [bp+var_2]
    mov     ax, word ptr [si]
    add     ax, word ptr [bp+var_8]
    mov     word ptr [bx], ax
    mov     ax, word ptr [si+0x2]
    add     ax, word ptr [bp+var_A]
    mov     word ptr [bx+0x2], ax
    add     word ptr [bp+var_2], 0x4
    add     word ptr [bp+var_4], 0x4
    inc     word ptr [bp+var_6]
    cmp     word ptr [bp+var_6], 0x10
    jl      LAB_36ec_003d
    pop     si
    mov     sp, bp
    pop     bp
    retf
preRender_wheel_helper_asm_ endp

seg023 ends
end
