; Generated by restunts-export.py (Ghidra)
.8086
.model medium

include seg026.inc

seg026 segment byte public use16 'STUNTSC'
    assume cs:seg026, es:nothing, ss:nothing, ds:dseg

; int __cdecl16far toupper(int __ch)
toupper_asm_ proc far
    __ch       = word ptr    6

    push    bp
    mov     bp, sp
    cmp     word ptr [bp+__ch], 0x61
    jl      LAB_370b_001d
    cmp     word ptr [bp+__ch], 0x7a
    jg      LAB_370b_001d
    sub     word ptr [bp+__ch], 0x20
LAB_370b_001d:
    mov     ax, word ptr [bp+__ch]
    pop     bp
    retf
toupper_asm_ endp

seg026 ends
end
