; Generated by restunts-export.py (Ghidra)
.8086
.model medium

include custom.inc
include structs.inc
include seg000.inc
include seg001.inc
include seg002.inc
include seg003.inc
include seg004.inc
include seg005.inc
include seg006.inc
include seg007.inc
include seg008.inc
include seg009.inc
include seg010.inc
include seg011.inc
include seg012.inc
include seg013.inc
include seg014.inc
include seg015.inc
include seg016.inc
include seg017.inc
include seg018.inc
include seg019.inc
include seg020.inc
include seg021.inc
include seg022.inc
include seg023.inc
include seg024.inc
include seg025.inc
include seg026.inc
include seg028.inc
include seg029.inc
include seg030.inc
include seg031.inc
include seg032.inc
include seg033.inc
include seg034.inc
include seg035.inc
include seg036.inc
include seg037.inc
include seg038.inc
include seg039.inc
include dseg.inc
include dsegu.inc

seg027 segment byte public use16 'STUNTSC'
    assume cs:seg027, es:nothing, ss:nothing, ds:dseg

    public init_audio_resources
    public load_audio_finalize
    public audio_unk
    public sub_372F4
    public sub_3736A
    public audio_enable_flag2
    public audio_disable_flag2
    public audio_toggle_flag2
    public nopsub_373FE
    public nopsub_37456
    public sub_37470
    public sub_374DE
    public audio_check_flag2
    public audio_check_flag
    public audio_init_chunk2
    public audio_enable_flag6
    public audio_disable_flag6
    public audio_toggle_flag6
    public sub_3771E
    public nopsub_37750
    public audio_driver_func3F
    public sub_37868
    public nopsub_37898
    public nopsub_378AE
    public nopsub_378BC
    public audio_load_driver
    public audiodrv_atexit
    public load_sfx_ge
    public nopsub_37C38
    public load_sfx_file
    public load_song_file
    public load_voice_file
    public nopsub_load_sample_file
    public audio_init_chunk
    public audio_map_song_instruments
    public nopsub_3803C
    public sub_38156
    public sub_38178
    public audio_map_song_tracks
    public off_383A0
    public audioresource_get_dword
    public audioresource_get_word
    public audioresource_copy_4_bytes
    public nopsub_debug_music

; void * __cdecl16far init_audio_resources(void * sng_file_ptr, void * vce_file_ptr, char * res_id)
init_audio_resources proc far
    var_titlptr = dword ptr -12
    var_8      = word ptr   -8
    var_6      = word ptr   -6
    var_hdrptr = dword ptr  -4
    sng_file_ptr = dword ptr   6
    vce_file_ptr = dword ptr  10
    res_id     = word ptr   14

    push    bp
    mov     bp, sp
    sub     sp, 0xc
    push    word ptr [bp+res_id]               ; res_id is a string, e.g "TITL"
    push    word ptr [bp+sng_file_ptr+2]
    push    word ptr [bp+sng_file_ptr]
    call    far ptr audioresource_find         ; audio_find_resource?
    add     sp, 0x6
    mov     word ptr [bp+var_titlptr], ax
    mov     word ptr [bp+var_titlptr+2], dx
    or      dx, ax
    jnz     LAB_370d_002a
LAB_370d_0023:
    sub     ax, ax
    cwd
    mov     sp, bp
    pop     bp
    retf
LAB_370d_002a:
    mov     ax, offset aHdr1
    push    ax
    push    word ptr [bp+var_titlptr+2]
    push    word ptr [bp+var_titlptr]
    call    far ptr audioresource_find         ; audio_find_resource? look up "hdr1" in the "TITL" chunk?
    add     sp, 0x6
    mov     word ptr [bp+var_hdrptr], ax
    mov     word ptr [bp+var_hdrptr+2], dx
    or      ax, dx
    jz      LAB_370d_0023
    les     bx, [bp+var_hdrptr]
    cmp     byte ptr es:[bx+0x5], 0x1          ; check header+5 if we already loaded this
    jz      LAB_370d_00a2
    push    word ptr [bp+vce_file_ptr+2]
    push    word ptr [bp+vce_file_ptr]
    push    word ptr [bp+var_titlptr+2]
    push    word ptr [bp+var_titlptr]
    push    cs
    call    near ptr audio_map_song_instruments
    add     sp, 0x8
    push    word ptr [bp+var_titlptr+2]
    push    word ptr [bp+var_titlptr]
    push    cs
    call    near ptr audio_map_song_tracks
    add     sp, 0x4
    les     bx, [bp+var_hdrptr]
    mov     byte ptr es:[bx+0x5], 0x1          ; set header+5 to 1, = loaded
    les     bx, [bp+var_titlptr]
    mov     al, byte ptr es:[bx+0x4]
    sub     ah, ah
    mov     cl, 0x3
    shl     ax, cl
    add     ax, bx
    mov     dx, es
    inc     ax
    mov     word ptr [bp+var_8], ax
    mov     word ptr [bp+var_6], dx
    lea     ax, [bp+var_8]
    push    ss
    push    ax
    push    word ptr [bp+var_hdrptr+2]
    push    word ptr [bp+var_hdrptr]
    push    cs
    call    near ptr audioresource_copy_4_bytes
; Notes on a kms file seem to 
; have four bytes...  
    add     sp, 0x8
LAB_370d_00a2:
    mov     ax, word ptr [bp+var_hdrptr]
    mov     dx, word ptr [bp+var_hdrptr+2]
    mov     sp, bp
    pop     bp
    retf
init_audio_resources endp

; void __cdecl16far load_audio_finalize(void * Mnote)
load_audio_finalize proc far
    var_6      = dword ptr  -6
    var_2      = word ptr   -2
    Mnote      = dword ptr   6

    push    bp
    mov     bp, sp
    sub     sp, 0x6
    push    si
    mov     word ptr [word_4063A], 0x1
    push    cs
    call    near ptr sub_3736A
    mov     ax, word ptr [bp+Mnote]
    or      ax, word ptr [bp+Mnote+2]
    jz      LAB_370d_013f
    les     bx, [bp+Mnote]
    cmp     byte ptr es:[bx+0x4], 0x0
    jnz     LAB_370d_013f
    cmp     byte ptr es:[bx+0x5], 0x1
    jnz     LAB_370d_013f
    mov     ax, word ptr [audiodriverbinary]
    mov     dx, word ptr [audiodriverbinary+2]
    add     ax, 0x18
    mov     word ptr [bp+var_6+2], dx
    mov     word ptr [bp+var_6], ax
    call    dword ptr [bp+var_6]
    mov     word ptr [word_44D48], 0x0
    mov     word ptr [word_454BA], 0x80
    les     bx, [bp+Mnote]
    mov     al, byte ptr es:[bx+0x6]
    sub     ah, ah
    shl     ax, 0x1
    shl     ax, 0x1
    add     ax, 0x7
    mov     word ptr [bp+var_2], ax
    mov     bx, ax
    inc     word ptr [bp+var_2]
    mov     si, word ptr [bp+Mnote]
    mov     al, byte ptr es:[bx+si]
    mov     byte ptr [byte_44290], al
    mov     ax, 0x20
    push    ax
    mov     al, byte ptr [byte_45950]
    sub     ah, ah
    push    ax
    push    word ptr [bp+var_2]
    push    es
    push    si
    mov     al, byte ptr [byte_44290]
    dec     ax
    push    ax
    sub     ax, ax
    push    ax
    push    cs
    call    near ptr audio_init_chunk
    add     sp, 0xe
    mov     byte ptr [byte_40632], 0x1
    mov     word ptr [word_4063A], 0x0
LAB_370d_013f:
    pop     si
    mov     sp, bp
    pop     bp
    retf
load_audio_finalize endp
    db 2 dup (0x90)

; void __cdecl16far audio_unk(void)
audio_unk proc far
    var_C      = word ptr  -12
    var_A      = dword ptr -10
    var_4      = word ptr   -4
    var_2      = word ptr   -2

    push    bp
    mov     bp, sp
    sub     sp, 0xc
    push    di
    push    si
    mov     byte ptr [byte_40630], 0x1
    mov     word ptr [word_4063A], 0x1
    cmp     byte ptr [byte_40634], 0x0
    jnz     LAB_370d_0192
    sub     si, si
    mov     di, 0x8224
LAB_370d_0165:
    cmp     byte ptr [audioflag6], 0x1
    jz      LAB_370d_0171
    cmp     si, 0x10
    jge     LAB_370d_0183
LAB_370d_0171:
    mov     al, byte ptr [di]
    mov     byte ptr [si+byte_428BE], al
    sub     ax, ax
    push    ax
    push    si
    call    far ptr audio_unk2
    add     sp, 0x4
LAB_370d_0183:
    add     di, 0x4c
    inc     si
    cmp     si, 0x18
    jl      LAB_370d_0165
    mov     word ptr [bp+var_2], si
    jmp     LAB_370d_01b6
    db 0x90
LAB_370d_0192:
    mov     byte ptr [byte_40639], 0x0
    mov     ax, offset unk_40636
    push    ds
    push    ax
    mov     ax, 0x4
    push    ax
    mov     ax, word ptr [audiodriverbinary]
    mov     dx, word ptr [audiodriverbinary+2]
    add     ax, 0x3f
    mov     word ptr [bp+var_A+2], dx
    mov     word ptr [bp+var_A], ax
    call    dword ptr [bp+var_A]
    add     sp, 0x6
LAB_370d_01b6:
    cmp     byte ptr [byte_40634], 0x0
    jnz     LAB_370d_0217
    mov     word ptr [bp+var_2], 0x10
    mov     di, 0xa2b6
    mov     word ptr [bp+var_C], 0x10
LAB_370d_01ca:
    mov     si, di
    push    word ptr [si+0x12]
    push    word ptr [si+0x10]
    push    word ptr [si+0x2a]
    push    si
    mov     al, byte ptr [si+0x2c]
    sub     ah, ah
    push    ax
    mov     ax, word ptr [audiodriverbinary]
    mov     dx, word ptr [audiodriverbinary+2]
    add     ax, 0x27
    mov     word ptr [bp+var_A+2], dx
    mov     word ptr [bp+var_A], ax
    call    dword ptr [bp+var_A]
    add     sp, 0xa
    add     di, 0x2e
    dec     word ptr [bp+var_C]
    jnz     LAB_370d_01ca
    mov     word ptr [bp+var_4], si
    mov     ax, 0xa2b6
    push    ax
    mov     ax, word ptr [audiodriverbinary]
    mov     dx, word ptr [audiodriverbinary+2]
    add     ax, 0x30
    mov     word ptr [bp+var_A+2], dx
    mov     word ptr [bp+var_A], ax
    call    dword ptr [bp+var_A]
    add     sp, 0x2
LAB_370d_0217:
    mov     word ptr [word_4063A], 0x0
    pop     si
    pop     di
    mov     sp, bp
    pop     bp
    retf
audio_unk endp
    db 0x90

; void __cdecl16far sub_372F4(void)
sub_372F4 proc far
    var_6      = dword ptr  -6
    var_2      = word ptr   -2

    push    bp
    mov     bp, sp
    sub     sp, 0x6
    push    si
    mov     byte ptr [byte_40630], 0x1
    mov     word ptr [word_4063A], 0x1
    cmp     byte ptr [byte_40634], 0x0
    jnz     LAB_370d_0266
    sub     si, si
LAB_370d_023f:
    cmp     byte ptr [audioflag6], 0x1
    jz      LAB_370d_024b
    cmp     si, 0x10
    jge     LAB_370d_025b
LAB_370d_024b:
    mov     al, byte ptr [si+byte_428BE]
    sub     ah, ah
    push    ax
    push    si
    call    far ptr audio_unk2
    add     sp, 0x4
LAB_370d_025b:
    inc     si
    cmp     si, 0x18
    jl      LAB_370d_023f
    mov     word ptr [bp+var_2], si
    jmp     LAB_370d_028a
LAB_370d_0266:
    mov     byte ptr [byte_40639], 0x64
    mov     ax, offset unk_40636
    push    ds
    push    ax
    mov     ax, 0x4
    push    ax
    mov     ax, word ptr [audiodriverbinary]
    mov     dx, word ptr [audiodriverbinary+2]
    add     ax, 0x3f
    mov     word ptr [bp+var_6+2], dx
    mov     word ptr [bp+var_6], ax
    call    dword ptr [bp+var_6]
    add     sp, 0x6
LAB_370d_028a:
    mov     word ptr [word_4063A], 0x0
    mov     byte ptr [byte_40630], 0x0
    pop     si
    mov     sp, bp
    pop     bp
    retf
sub_372F4 endp

; void __cdecl16far sub_3736A(void)
sub_3736A proc far
    mov     word ptr [word_4063A], 0x1
    mov     byte ptr [byte_40632], 0x0
    mov     ax, 0xf
    push    ax
    sub     ax, ax
    push    ax
    call    far ptr audio_driver_func1E
    add     sp, 0x4
    sub     ax, ax
    push    ax
    mov     al, byte ptr [byte_45950]
    sub     ah, ah
    push    ax
    sub     ax, ax
    push    ax
    push    ax
    push    ax
    mov     ax, 0xf
    push    ax
    sub     ax, ax
    push    ax
    push    cs
    call    near ptr audio_init_chunk
    add     sp, 0xe
    mov     byte ptr [byte_44290], 0x0
    call    far ptr sub_39700
    mov     word ptr [word_4063A], 0x0
    retf
sub_3736A endp
    db 0x90

; void __cdecl16far audio_enable_flag2(void)
audio_enable_flag2 proc far
    mov     byte ptr [audioflag2], 0x1
    retf
audio_enable_flag2 endp

; void __cdecl16far audio_disable_flag2(void)
audio_disable_flag2 proc far
    mov     byte ptr [audioflag2], 0x0
    mov     word ptr [word_4063A], 0x1
    cmp     byte ptr [byte_44290], 0x0
    jz      LAB_370d_030c
    mov     al, byte ptr [byte_44290]
    sub     ah, ah
    dec     ax
    push    ax
    sub     ax, ax
    push    ax
    call    far ptr audio_driver_func1E
    add     sp, 0x4
LAB_370d_030c:
    call    far ptr sub_39700
    mov     word ptr [word_4063A], 0x0
    retf
audio_disable_flag2 endp

; int __cdecl16far audio_toggle_flag2(void)
audio_toggle_flag2 proc far
    cmp     byte ptr [audioflag2], 0x1
    jnz     LAB_370d_0326
    push    cs
    call    near ptr audio_disable_flag2
    sub     ax, ax
    retf
LAB_370d_0326:
    push    cs
    call    near ptr audio_enable_flag2
    mov     ax, 0x1
    retf
audio_toggle_flag2 endp

; int __cdecl16far nopsub_373FE(void)
nopsub_373FE proc far
    var_2      = word ptr   -2

    push    bp
    mov     bp, sp
    sub     sp, 0x6
    push    di
    push    si
    cmp     byte ptr [byte_40630], 0x1
    jz      LAB_370d_0344
    cmp     byte ptr [audioflag2], 0x0
    jnz     LAB_370d_034e
LAB_370d_0344:
    mov     ax, 0x1
    pop     si
    pop     di
    mov     sp, bp
    pop     bp
    retf
    db 0x90
LAB_370d_034e:
    mov     word ptr [bp+var_2], 0x0
    mov     al, byte ptr [byte_44290]
    sub     ah, ah
    or      ax, ax
    jz      LAB_370d_0344
    mov     di, ax
    mov     si, 0x81fc
    mov     cx, word ptr [bp+var_2]
LAB_370d_0364:
    mov     ax, word ptr [si]
    or      ax, word ptr [si+0x2]
    jz      LAB_370d_0376
    sub     ax, ax
    mov     word ptr [bp+var_2], cx
    pop     si
    pop     di
    mov     sp, bp
    pop     bp
    retf
LAB_370d_0376:
    add     si, 0x4c
    inc     cx
    mov     ax, cx
    cmp     ax, di
    jc      LAB_370d_0364
    mov     word ptr [bp+var_2], cx
    jmp     LAB_370d_0344
nopsub_373FE endp
    db 0x90

; void __cdecl16far nopsub_37456(undefined2 param_1, undefined2 param_2)
nopsub_37456 proc far
    param_1    = word ptr    6
    param_2    = word ptr    8

    push    bp
    mov     bp, sp
    mov     ax, 0x40
    push    ax
    mov     ax, 0xffff
    push    ax
    push    word ptr [bp+param_2]
    push    word ptr [bp+param_1]
    push    cs
    call    near ptr audio_check_flag2
    add     sp, 0x8
    pop     bp
    retf
nopsub_37456 endp

; int __cdecl16far sub_37470(int param_1, byte param_2)
sub_37470 proc far
    var_2      = word ptr   -2
    param_1    = word ptr    6
    param_2    = byte ptr    8

    push    bp
    mov     bp, sp
    sub     sp, 0x4
    push    di
    push    si
    cmp     word ptr [bp+param_1], -0x1
    jnz     LAB_370d_03fe
    mov     si, 0x10
    mov     di, 0x86bc
    mov     cx, word ptr [bp+param_1]
LAB_370d_03b7:
    cmp     cx, -0x1
    jnz     LAB_370d_03d5
    mov     ax, word ptr [di]
    or      ax, word ptr [di+0x2]
    jnz     LAB_370d_03cc
    cmp     byte ptr [si+byte_45D9A], 0x0
    jnz     LAB_370d_03cc
    mov     cx, si
LAB_370d_03cc:
    add     di, 0x4c
    inc     si
    cmp     si, 0x17
    jle     LAB_370d_03b7
LAB_370d_03d5:
    mov     word ptr [bp+var_2], si
    mov     word ptr [bp+param_1], cx
    cmp     cx, -0x1
    jz      LAB_370d_03f5
    mov     bx, cx
    mov     byte ptr [bx+byte_45D9A], 0x1
    mov     ax, 0x4c
    imul    cx
LAB_370d_03ec:
    mov     bx, ax
    mov     al, byte ptr [bp+param_2]
    mov     byte ptr [bx+(audiochunks_unk+36)], al
LAB_370d_03f5:
    mov     ax, word ptr [bp+param_1]
    pop     si
    pop     di
    mov     sp, bp
    pop     bp
    retf
LAB_370d_03fe:
    mov     bx, word ptr [bp+param_1]
    mov     byte ptr [bx+byte_45D9A], 0x1
    mov     ax, 0x4c
    imul    bx
    jmp     LAB_370d_03ec
sub_37470 endp
    db 0x90

; void __cdecl16far sub_374DE(uint param_1)
sub_374DE proc far
    param_1    = word ptr    6

    push    bp
    mov     bp, sp
    cmp     word ptr [bp+param_1], -0x1
    jle     LAB_370d_0427
    mov     bx, word ptr [bp+param_1]
    mov     byte ptr [bx+byte_45D9A], 0x0
    push    bx
    push    cs
    call    near ptr audio_init_chunk2
    add     sp, 0x2
LAB_370d_0427:
    pop     bp
    retf
sub_374DE endp
    db 0x90

; void __cdecl16far audio_check_flag2(undefined2 param_1, undefined2 param_2, uint param_3, byte param_4)
audio_check_flag2 proc far
    param_1    = word ptr    6
    param_2    = word ptr    8
    param_3    = word ptr   10
    param_4    = byte ptr   12

    push    bp
    mov     bp, sp
    mov     al, byte ptr [byte_45948]
    sub     ah, ah
    push    ax
    mov     al, byte ptr [bp+param_4]
    push    ax
    push    word ptr [bp+param_3]
    push    word ptr [bp+param_2]
    push    word ptr [bp+param_1]
    push    cs
    call    near ptr audio_check_flag
    add     sp, 0xa
    pop     bp
    retf
audio_check_flag2 endp
    db 0x90

; int __cdecl16far audio_check_flag(undefined4 param_1, int param_2, byte param_3, int param_4)
audio_check_flag proc far
    var_6      = word ptr   -6
    var_4      = word ptr   -4
    var_2      = word ptr   -2
    param_1    = dword ptr   6
    param_2    = word ptr   10
    param_3    = byte ptr   12
    param_4    = word ptr   14

    push    bp
    mov     bp, sp
    sub     sp, 0x8
    push    di
    push    si
    cmp     byte ptr [audioflag6], 0x0
    jnz     LAB_370d_0462
LAB_370d_0459:
    mov     ax, 0xffff
    pop     si
    pop     di
    mov     sp, bp
    pop     bp
    retf
LAB_370d_0462:
    mov     ax, word ptr [bp+param_1]
    or      ax, word ptr [bp+param_1+2]
    jz      LAB_370d_0459
    les     bx, [bp+param_1]
    cmp     byte ptr es:[bx+0x5], 0x1
    jnz     LAB_370d_0459
    cmp     byte ptr [byte_45948], 0x0
    jz      LAB_370d_0498
    mov     al, byte ptr [byte_45948]
    sub     ah, ah
    mov     cx, ax
    mov     ax, word ptr [bp+param_4]
    mov     dx, cx
    mov     cl, 0x7
    shl     ax, cl
    mov     cx, dx
    sub     dx, dx
    div     cx
    dec     ax
    mov     word ptr [bp+param_4], ax
    jmp     LAB_370d_049d
    db 0x90
LAB_370d_0498:
    mov     word ptr [bp+param_4], 0x0
LAB_370d_049d:
    cmp     word ptr [bp+param_2], -0x1
    jz      LAB_370d_04a6
    jmp     near ptr LAB_370d_0539
LAB_370d_04a6:
    mov     si, 0x10
    mov     di, offset audiochunks_unk2
    mov     cx, word ptr [bp+param_2]
LAB_370d_04af:
    cmp     cx, -0x1
    jnz     LAB_370d_04cd
    mov     ax, word ptr [di]
    or      ax, word ptr [di+0x2]
    jnz     LAB_370d_04c4
    cmp     byte ptr [si+byte_45D9A], 0x0
    jnz     LAB_370d_04c4
    mov     cx, si
LAB_370d_04c4:
    add     di, 0x4c
    inc     si
    cmp     si, 0x17
    jle     LAB_370d_04af
LAB_370d_04cd:
    mov     word ptr [bp+var_4], si
    mov     word ptr [bp+param_2], cx
    cmp     cx, -0x1
    jnz     LAB_370d_0539
    mov     cx, 0xff
    mov     di, 0x10
    mov     si, 0x86e0
    mov     dx, word ptr [bp+param_2]
LAB_370d_04e4:
    mov     al, byte ptr [si]
    sub     ah, ah
    cmp     ax, cx
    ja      LAB_370d_04fb
    mov     ax, offset byte_45D9A
    or      ax, ax
    jnz     LAB_370d_04fb
    mov     al, byte ptr [si]
    sub     ah, ah
    mov     cx, ax
    mov     dx, di
LAB_370d_04fb:
    add     si, 0x4c
    inc     di
    cmp     di, 0x17
    jl      LAB_370d_04e4
    mov     word ptr [bp+var_4], di
    mov     word ptr [bp+param_2], dx
    mov     word ptr [bp+var_6], cx
    cmp     dx, -0x1
    jz      LAB_370d_0539
    mov     ax, 0x4c
    imul    dx
    mov     bx, ax
    mov     al, byte ptr [bp+param_3]
    cmp     byte ptr [bx+(audiochunks_unk+36)], al
    ja      LAB_370d_0539
    mov     bx, word ptr [bp+param_2]
    cmp     byte ptr [bx+byte_45D9A], 0x0
    jz      LAB_370d_0531
    mov     byte ptr [bx+byte_45D9A], 0x0
LAB_370d_0531:
    push    bx
    push    cs
    call    near ptr audio_init_chunk2
    add     sp, 0x2
LAB_370d_0539:
    cmp     word ptr [bp+param_2], -0x1
    jnz     LAB_370d_0542
    jmp     near ptr LAB_370d_0459
LAB_370d_0542:
    les     bx, [bp+param_1]
    mov     al, byte ptr es:[bx+0x6]
    sub     ah, ah
    shl     ax, 0x1
    shl     ax, 0x1
    add     ax, 0x8
    mov     word ptr [bp+var_2], ax
    mov     al, byte ptr [bp+param_3]
    sub     ah, ah
    push    ax
    push    word ptr [bp+param_4]
    push    word ptr [bp+var_2]
    push    es
    push    bx
    push    word ptr [bp+param_2]
    push    word ptr [bp+param_2]
    push    cs
    call    near ptr audio_init_chunk
    add     sp, 0xe
    mov     ax, word ptr [bp+param_2]
    pop     si
    pop     di
    mov     sp, bp
    pop     bp
    retf
audio_check_flag endp
    db 0x90

; void __cdecl16far audio_init_chunk2(uint param_1)
audio_init_chunk2 proc far
    param_1    = word ptr    6

    push    bp
    mov     bp, sp
    cmp     word ptr [bp+param_1], 0x10
    jl      LAB_370d_05c4
    cmp     word ptr [bp+param_1], 0x17
    jg      LAB_370d_05c4
    mov     ax, 0x4c
    imul    word ptr [bp+param_1]
    mov     bx, ax
    sub     ax, ax
    mov     word ptr [bx+(audiochunks_unk+2)], ax
    mov     word ptr [bx+audiochunks_unk], ax
    push    word ptr [bp+param_1]
    push    word ptr [bp+param_1]
    call    far ptr audio_driver_func1E
    add     sp, 0x4
    sub     ax, ax
    push    ax
    mov     al, byte ptr [byte_45948]
    sub     ah, ah
    push    ax
    sub     ax, ax
    push    ax
    push    ax
    push    ax
    push    word ptr [bp+param_1]
    push    word ptr [bp+param_1]
    push    cs
    call    near ptr audio_init_chunk
    add     sp, 0xe
LAB_370d_05c4:
    pop     bp
    retf
audio_init_chunk2 endp

; void __cdecl16far audio_enable_flag6(void)
audio_enable_flag6 proc far
    var_2      = word ptr   -2

    push    bp
    mov     bp, sp
    sub     sp, 0x2
    push    si
    cmp     byte ptr [audioflag6], 0x1
    jz      LAB_370d_05f5
    mov     si, 0x10
LAB_370d_05d7:
    mov     al, byte ptr [si+byte_428D6]
    sub     ah, ah
    push    ax
    push    si
    call    far ptr audio_unk2
    add     sp, 0x4
    inc     si
    cmp     si, 0x18
    jl      LAB_370d_05d7
    mov     word ptr [bp+var_2], si
    mov     byte ptr [audioflag6], 0x1
LAB_370d_05f5:
    pop     si
    mov     sp, bp
    pop     bp
    retf
audio_enable_flag6 endp

; void __cdecl16far audio_disable_flag6(void)
audio_disable_flag6 proc far
    var_2      = word ptr   -2

    push    bp
    mov     bp, sp
    sub     sp, 0x4
    push    di
    push    si
    cmp     byte ptr [audioflag6], 0x0
    jz      LAB_370d_0632
    mov     si, 0x10
    mov     di, offset (audiochunks_unk2+40)
LAB_370d_060f:
    mov     al, byte ptr [di]
    mov     byte ptr [si+byte_428D6], al
    sub     ax, ax
    push    ax
    push    si
    call    far ptr audio_unk2
    add     sp, 0x4
    add     di, 0x4c
    inc     si
    cmp     si, 0x18
    jl      LAB_370d_060f
    mov     word ptr [bp+var_2], si
    mov     byte ptr [audioflag6], 0x0
LAB_370d_0632:
    pop     si
    pop     di
    mov     sp, bp
    pop     bp
    retf
audio_disable_flag6 endp

; int __cdecl16far audio_toggle_flag6(void)
audio_toggle_flag6 proc far
    cmp     byte ptr [audioflag6], 0x1
    jnz     LAB_370d_0646
    push    cs
    call    near ptr audio_disable_flag6
    sub     ax, ax
    retf
LAB_370d_0646:
    push    cs
    call    near ptr audio_enable_flag6
    mov     ax, 0x1
    retf
audio_toggle_flag6 endp

; int __cdecl16far sub_3771E(int param_1)
sub_3771E proc far
    param_1    = word ptr    6

    push    bp
    mov     bp, sp
    cmp     byte ptr [audioflag6], 0x0
    jnz     LAB_370d_065e
LAB_370d_0658:
    mov     ax, 0x1
    pop     bp
    retf
    db 0x90
LAB_370d_065e:
    cmp     word ptr [bp+param_1], 0x10
    jl      LAB_370d_0658
    cmp     word ptr [bp+param_1], 0x17
    jg      LAB_370d_0658
    mov     ax, 0x4c
    imul    word ptr [bp+param_1]
    mov     bx, ax
    mov     ax, word ptr [bx+audiochunks_unk]
    or      ax, word ptr [bx+(audiochunks_unk+2)]
    jz      LAB_370d_0658
    sub     ax, ax
    pop     bp
    retf
sub_3771E endp

; void __cdecl16far nopsub_37750(int param_1, undefined2 param_2, undefined2 param_3)
nopsub_37750 proc far
    param_1    = word ptr    6
    param_2    = word ptr    8
    param_3    = word ptr   10

    push    bp
    mov     bp, sp
    mov     ax, 0x4c
    mul     word ptr [bp+param_1]
    mov     bx, ax
    mov     ax, word ptr [bp+param_2]
    mov     dx, word ptr [bp+param_3]
    mov     word ptr [bx+(audiochunks_unk+72)], ax
    mov     word ptr [bx+(audiochunks_unk+74)], dx
    pop     bp
    retf
nopsub_37750 endp
    db 0x90

; void __cdecl16far audio_driver_func3F(word param_1)
audio_driver_func3F proc far
    var_A      = dword ptr -10
    var_6      = word ptr   -6
    var_4      = word ptr   -4
    var_2      = word ptr   -2
    param_1    = word ptr    6

    push    bp
    mov     bp, sp
    sub     sp, 0xa
    push    si
    cmp     byte ptr [byte_40634], 0x0
    jnz     LAB_370d_06f6
    mov     al, byte ptr [byte_45950]
    sub     ah, ah
    mov     word ptr [bp+var_2], ax
    or      ax, ax
    jg      LAB_370d_06b9
    jmp     near ptr LAB_370d_0750
LAB_370d_06b9:
    mov     ax, word ptr [bp+param_1]
    cwd
    mov     word ptr [bp+var_6], ax
    mov     word ptr [bp+var_4], dx
    mov     si, word ptr [bp+var_2]
LAB_370d_06c6:
    mov     word ptr [word_4063A], 0x1
    push    si
    push    cs
    call    near ptr sub_37868
    add     sp, 0x2
    mov     word ptr [word_4063A], 0x0
    push    word ptr [bp+var_4]
    push    word ptr [bp+var_6]
    call    far ptr timer_copy_counter
    add     sp, 0x4
    call    far ptr timer_wait_for_dx
    sub     si, 0x2
    or      si, si
    jg      LAB_370d_06c6
    jmp     LAB_370d_074d
LAB_370d_06f6:
    mov     si, 0x64
    mov     ax, word ptr [bp+param_1]
    cwd
    mov     word ptr [bp+var_6], ax
    mov     word ptr [bp+var_4], dx
LAB_370d_0703:
    mov     word ptr [word_4063A], 0x1
    mov     ax, si
    mov     byte ptr [byte_40639], al
    mov     ax, offset unk_40636
    push    ds
    push    ax
    mov     ax, 0x4
    push    ax
    mov     ax, word ptr [audiodriverbinary]
    mov     dx, word ptr [audiodriverbinary+2]
    add     ax, 0x3f
    mov     word ptr [bp+var_A+2], dx
    mov     word ptr [bp+var_A], ax
    call    dword ptr [bp+var_A]
    add     sp, 0x6
    mov     word ptr [word_4063A], 0x0
    push    word ptr [bp+var_4]
    push    word ptr [bp+var_6]
    call    far ptr timer_copy_counter
    add     sp, 0x4
    call    far ptr timer_wait_for_dx
    sub     si, 0x2
    or      si, si
    jg      LAB_370d_0703
LAB_370d_074d:
    mov     word ptr [bp+var_2], si
LAB_370d_0750:
    push    cs
    call    near ptr sub_3736A
    cmp     byte ptr [byte_40634], 0x0
    jz      LAB_370d_0792
    mov     ax, 0x32
    cwd
    push    dx
    push    ax
    call    far ptr timer_copy_counter
    add     sp, 0x4
    call    far ptr timer_wait_for_dx
    mov     byte ptr [byte_40639], 0x64
    mov     ax, offset unk_40636
    push    ds
    push    ax
    mov     ax, 0x4
    push    ax
    mov     ax, word ptr [audiodriverbinary]
    mov     dx, word ptr [audiodriverbinary+2]
    add     ax, 0x3f
    mov     word ptr [bp+var_A+2], dx
    mov     word ptr [bp+var_A], ax
    call    dword ptr [bp+var_A]
    add     sp, 0x6
LAB_370d_0792:
    pop     si
    mov     sp, bp
    pop     bp
    retf
audio_driver_func3F endp
    db 0x90

; void __cdecl16far sub_37868(byte param_1)
sub_37868 proc far
    var_2      = word ptr   -2
    param_1    = byte ptr    6

    push    bp
    mov     bp, sp
    sub     sp, 0x2
    push    di
    push    si
    sub     si, si
    mov     di, word ptr [bp+param_1]
    jmp     LAB_370d_07b3
    db 0x90
LAB_370d_07a8:
    push    di
    push    si
    call    far ptr audio_unk2
    add     sp, 0x4
    inc     si
LAB_370d_07b3:
    mov     ax, si
    mov     cl, byte ptr [byte_44290]
    sub     ch, ch
    cmp     ax, cx
    jc      LAB_370d_07a8
    mov     word ptr [bp+var_2], si
    pop     si
    pop     di
    mov     sp, bp
    pop     bp
    retf
sub_37868 endp

; void __cdecl16far nopsub_37898(byte param_1)
nopsub_37898 proc far
    param_1    = byte ptr    6

    push    bp
    mov     bp, sp
    mov     al, byte ptr [bp+param_1]
    mov     byte ptr [byte_45950], al
    push    word ptr [bp+param_1]
    push    cs
    call    near ptr sub_37868
    add     sp, 0x2
    pop     bp
    retf
nopsub_37898 endp
    db 0x90

; byte __cdecl16far nopsub_378AE(int param_1)
nopsub_378AE proc far
    param_1    = word ptr    6

    push    bp
    mov     bp, sp
    mov     bx, word ptr [bp+param_1]
    mov     al, byte ptr [bx+byte_44D06]
    sub     ah, ah
    pop     bp
    retf
nopsub_378AE endp

; byte __cdecl16far nopsub_378BC(int param_1)
nopsub_378BC proc far
    param_1    = word ptr    6

    push    bp
    mov     bp, sp
    mov     bx, word ptr [bp+param_1]
    mov     al, byte ptr [bx+byte_44ACA]
    sub     ah, ah
    pop     bp
    retf
nopsub_378BC endp

; short __cdecl16far audio_load_driver(char * driver, short param_2, char * param_3)
audio_load_driver proc far
    var_C      = dword ptr -12
    var_8      = word ptr   -8
    var_6      = word ptr   -6
    var_4      = word ptr   -4
    var_2      = word ptr   -2
    driver     = word ptr    6
    param_2    = word ptr    8
    param_3    = word ptr   10

    push    bp
    mov     bp, sp
    sub     sp, 0xc
    push    di
    push    si
    cmp     word ptr [bp+param_3], 0x473a
    jnz     LAB_370d_080e
    mov     byte ptr [g_auddrv_d], 0x1
LAB_370d_080e:
    mov     ax, word ptr [audiodriverbinary]
    or      ax, word ptr [audiodriverbinary+2]
    jz      LAB_370d_081e
    push    cs
    call    near ptr audiodrv_atexit
    jmp     LAB_370d_082e
    db 0x90
LAB_370d_081e:
    mov     ax, offset audiodrv_atexit
; <REPLACE>
    mov     dx, seg seg027
; </REPLACE>
;    mov     dx, 0x370d
    push    dx
    push    ax
    call    far ptr add_exit_handler
    add     sp, 0x4
LAB_370d_082e:
    sub     ax, ax
    mov     word ptr [audiodriverbinary+2], ax
    mov     word ptr [audiodriverbinary], ax
    push    ds
    pop     es
    mov     di, word ptr [bp+driver]
    mov     cx, 0xffff
    xor     ax, ax
    repne scasb
    not     cx
    dec     cx
    mov     word ptr [bp+var_8], cx
    or      cx, cx
    jz      LAB_370d_0862
    mov     dx, word ptr [bp+driver]
LAB_370d_084f:
    mov     bx, cx
    mov     si, dx
    cmp     byte ptr [bx+si], 0x5c
    jz      LAB_370d_085f
    cmp     byte ptr [bx+si], 0x3a
    jz      LAB_370d_085f
    loop    LAB_370d_084f
LAB_370d_085f:
    mov     word ptr [bp+var_8], cx
LAB_370d_0862:
    cmp     word ptr [bp+var_8], 0x0
    jz      LAB_370d_086b
    inc     word ptr [bp+var_8]
LAB_370d_086b:
    mov     si, word ptr [bp+var_8]
    add     si, word ptr [bp+driver]
    mov     al, byte ptr [si]
    mov     byte ptr [audiodriverstring2], al
    mov     al, byte ptr [si+0x1]
    mov     byte ptr [(audiodriverstring2+1)], al
    mov     byte ptr [(audiodriverstring2+2)], 0x0
    mov     ax, offset unk_4063E
    push    ax                                 ; int
    mov     ax, offset aDrv
    push    ax
    push    word ptr [bp+driver]               ; char *
    call    far ptr audio_make_filename
    add     sp, 0x6
    mov     word ptr [bp+var_6], ax
    push    ax
    call    far ptr file_load_binary_nofatal
    add     sp, 0x2
    mov     word ptr [audiodriverbinary], ax
    mov     word ptr [audiodriverbinary+2], dx
    mov     byte ptr [byte_45950], 0x7f
    mov     byte ptr [byte_45948], 0x7f
    or      ax, dx
    jnz     LAB_370d_08b8
    jmp     near ptr LAB_370d_0982
LAB_370d_08b8:
    call    dword ptr [audiodriverbinary]
    mov     byte ptr [byte_459D2], al
    or      al, al
    jz      LAB_370d_08c7
    cmp     al, 0xff
    jnz     LAB_370d_08d2
LAB_370d_08c7:
    mov     ax, 0x2
    pop     si
    pop     di
    mov     sp, bp
    pop     bp
    retf
    db 2 dup (0x90)
LAB_370d_08d2:
    cmp     byte ptr [byte_459D2], 0x7f
    jbe     LAB_370d_08e8
    mov     byte ptr [byte_459D2], 0x10
    mov     byte ptr [byte_40634], 0x1
    mov     byte ptr [g_auddrv_d], 0x0
LAB_370d_08e8:
    push    cs
    call    near ptr sub_38178
    mov     ax, offset audiodriver_timer
; <REPLACE>
    mov     dx, seg seg028
; </REPLACE>
;    mov     dx, 0x3863
    push    dx
    push    ax
    call    far ptr timer_reg_callback
    add     sp, 0x4
    cmp     byte ptr [byte_40634], 0x0
    jz      LAB_370d_0965
    mov     ax, offset aMt32_plb
    push    ax
    call    far ptr file_load_binary_nofatal
    add     sp, 0x2
    mov     word ptr [bp+var_4], ax
    mov     word ptr [bp+var_2], dx
    or      ax, dx
    jz      LAB_370d_0965
    push    dx
    push    word ptr [bp+var_4]
    mov     ax, word ptr [audiodriverbinary]
    mov     dx, word ptr [audiodriverbinary+2]
    add     ax, 0x42
    mov     word ptr [bp+var_C+2], dx
    mov     word ptr [bp+var_C], ax
    call    dword ptr [bp+var_C]
    add     sp, 0x4
    push    word ptr [bp+var_2]
    push    word ptr [bp+var_4]
    call    far ptr mmgr_release
    add     sp, 0x4
    mov     byte ptr [byte_40639], 0x64
    mov     ax, offset unk_40636
    push    ds
    push    ax
    mov     ax, 0x4
    push    ax
    mov     ax, word ptr [audiodriverbinary]
    mov     dx, word ptr [audiodriverbinary+2]
    add     ax, 0x3f
    mov     word ptr [bp+var_C+2], dx
    mov     word ptr [bp+var_C], ax
    call    dword ptr [bp+var_C]
    add     sp, 0x6
LAB_370d_0965:
    mov     byte ptr [byte_40630], 0x0
    mov     byte ptr [audioflag2], 0x1
    mov     byte ptr [byte_40632], 0x0
    mov     byte ptr [audioflag6], 0x1
    sub     ax, ax
    pop     si
    pop     di
    mov     sp, bp
    pop     bp
    retf
    db 0x90
LAB_370d_0982:
    mov     ax, offset aCanTFindDriver
    push    ax
    call    far ptr fatal_error
audio_load_driver endp
    add     sp, 0x2
    pop     si
    pop     di
    mov     sp, bp
    pop     bp
    retf

; void __cdecl16far audiodrv_atexit(void)
audiodrv_atexit proc far
    var_4      = dword ptr  -4

    push    bp
    mov     bp, sp
    sub     sp, 0x4
    mov     word ptr [word_4063A], 0x1
    mov     ax, word ptr [audiodriverbinary]
    or      ax, word ptr [audiodriverbinary+2]
    jnz     LAB_370d_09ac
    jmp     near ptr LAB_370d_0a39
LAB_370d_09ac:
    mov     ax, 0xc
; <REPLACE>
    mov     dx, seg seg028
; </REPLACE>
;    mov     dx, 0x3863
    push    dx
    push    ax
    call    far ptr timer_remove_callback
    add     sp, 0x4
    mov     byte ptr [audioflag2], 0x0
    mov     byte ptr [audioflag6], 0x0
    cmp     byte ptr [byte_40634], 0x0
    jz      LAB_370d_09f1
    mov     byte ptr [byte_40639], 0x64
    mov     ax, 0x4ec6
    push    ds
    push    ax
    mov     ax, 0x4
    push    ax
    mov     ax, word ptr [audiodriverbinary]
    mov     dx, word ptr [audiodriverbinary+2]
    add     ax, 0x3f
    mov     word ptr [bp+var_4+2], dx
    mov     word ptr [bp+var_4], ax
    call    dword ptr [bp+var_4]
    add     sp, 0x6
LAB_370d_09f1:
    mov     ax, word ptr [audiodriverbinary]
    mov     dx, word ptr [audiodriverbinary+2]
    add     ax, 0x6
    mov     word ptr [bp+var_4+2], dx
    mov     word ptr [bp+var_4], ax
    call    dword ptr [bp+var_4]
    mov     ax, word ptr [audiodriverbinary]
    mov     dx, word ptr [audiodriverbinary+2]
    add     ax, 0x3
    mov     word ptr [bp+var_4+2], dx
    mov     word ptr [bp+var_4], ax
    call    dword ptr [bp+var_4]
    push    word ptr [audiodriverbinary+2]
    push    word ptr [audiodriverbinary]
    call    far ptr mmgr_release
    add     sp, 0x4
    sub     ax, ax
    mov     word ptr [audiodriverbinary+2], ax
    mov     word ptr [audiodriverbinary], ax
    mov     byte ptr [byte_40634], 0x0
    mov     byte ptr [g_auddrv_d], 0x0
LAB_370d_0a39:
    mov     word ptr [word_4063A], 0x0
    mov     sp, bp
    pop     bp
    retf
audiodrv_atexit endp
    db 0x90

; void * __cdecl16far load_sfx_ge(char * filename, char * extension, char * audiodriver)
load_sfx_ge proc far
    var_8      = byte ptr   -8
    var_7      = byte ptr   -7
    var_6      = byte ptr   -6
    var_5      = byte ptr   -5
    var_4      = word ptr   -4
    var_2      = word ptr   -2
    filename   = word ptr    6
    extension  = word ptr    8
    audiodriver = word ptr   10

    push    bp
    mov     bp, sp
    sub     sp, 0x8
    push    word ptr [bp+audiodriver]          ; int
    push    word ptr [bp+extension]
    push    word ptr [bp+filename]             ; char *
    call    far ptr audio_make_filename
    add     sp, 0x6
    push    ax
    call    far ptr file_load_binary_nofatal
    add     sp, 0x2
    mov     word ptr [bp+var_4], ax
    mov     word ptr [bp+var_2], dx
    or      ax, dx
    jz      LAB_370d_0a78
LAB_370d_0a6e:
    mov     ax, word ptr [bp+var_4]
    mov     dx, word ptr [bp+var_2]
    mov     sp, bp
    pop     bp
    retf
LAB_370d_0a78:
    mov     byte ptr [bp+var_8], 0x50
    mov     bx, word ptr [bp+extension]
    mov     al, byte ptr [bx]
    mov     byte ptr [bp+var_7], al
    mov     al, byte ptr [bx+0x1]
    mov     byte ptr [bp+var_6], al
    mov     byte ptr [bp+var_5], 0x0
    push    word ptr [bp+audiodriver]          ; int
    lea     ax, [bp+var_8]
    push    ax
    push    word ptr [bp+filename]             ; char *
    call    far ptr audio_make_filename
    add     sp, 0x6
    push    ax
    call    far ptr file_decomp_nofatal
    add     sp, 0x2
    mov     word ptr [bp+var_4], ax
    mov     word ptr [bp+var_2], dx
    or      ax, dx
    jnz     LAB_370d_0a6e
    mov     ax, offset aGe
    push    ax                                 ; int
    push    word ptr [bp+extension]
    push    word ptr [bp+filename]             ; char *
    call    far ptr audio_make_filename
    add     sp, 0x6
    push    ax
    call    far ptr file_load_binary_nofatal
    add     sp, 0x2
    mov     word ptr [bp+var_4], ax
    mov     word ptr [bp+var_2], dx
    or      ax, dx
    jnz     LAB_370d_0a6e
    mov     ax, offset aGe_0
    push    ax                                 ; int
    lea     ax, [bp+var_8]
    push    ax
    push    word ptr [bp+filename]             ; char *
    call    far ptr audio_make_filename
    add     sp, 0x6
    push    ax
    call    far ptr file_decomp_nofatal
    add     sp, 0x2
    mov     word ptr [bp+var_4], ax
    mov     word ptr [bp+var_2], dx
    or      ax, dx
    jz      LAB_370d_0b01
    jmp     near ptr LAB_370d_0a6e
LAB_370d_0b01:
    mov     ax, offset aBlankstr
    push    ax                                 ; int
    push    word ptr [bp+extension]
    push    word ptr [bp+filename]             ; char *
    call    far ptr audio_make_filename
    add     sp, 0x6
    push    ax
    call    far ptr file_load_binary_nofatal
    add     sp, 0x2
    mov     word ptr [bp+var_4], ax
    mov     word ptr [bp+var_2], dx
    or      ax, dx
    jz      LAB_370d_0b29
    jmp     near ptr LAB_370d_0a6e
LAB_370d_0b29:
    mov     ax, offset aBlankstr2
    push    ax                                 ; int
    lea     ax, [bp+var_8]
    push    ax
    push    word ptr [bp+filename]             ; char *
    call    far ptr audio_make_filename
    add     sp, 0x6
    push    ax
    call    far ptr file_decomp_nofatal
    add     sp, 0x2
    mov     word ptr [bp+var_4], ax
    mov     word ptr [bp+var_2], dx
    or      ax, dx
    jz      LAB_370d_0b52
    jmp     near ptr LAB_370d_0a6e
LAB_370d_0b52:
    push    word ptr [bp+filename]
    call    far ptr file_load_binary_nofatal
    add     sp, 0x2
    mov     word ptr [bp+var_4], ax
    mov     word ptr [bp+var_2], dx
    or      ax, dx
    jmp     near ptr LAB_370d_0a6e
load_sfx_ge endp

; void __cdecl16far nopsub_37C38(word param_1)
nopsub_37C38 proc far
    param_1    = word ptr    6

    push    bp
    mov     bp, sp
    mov     ax, word ptr [bp+param_1]
    mov     word ptr [word_4063C], ax
    pop     bp
    retf
nopsub_37C38 endp
    db 0x90

; void * __cdecl16far load_sfx_file(char * filename)
load_sfx_file proc far
    var_4      = word ptr   -4
    var_2      = word ptr   -2
    filename   = word ptr    6

    push    bp
    mov     bp, sp
    sub     sp, 0x4
    sub     ax, ax
    mov     word ptr [bp+var_2], ax
    mov     word ptr [bp+var_4], ax
    cmp     byte ptr [g_auddrv_d], 0x0
    jz      LAB_370d_0ba1
    mov     ax, offset audiodriverstring2
    push    ax                                 ; int
    mov     ax, offset aDsf
    push    ax
    push    word ptr [bp+filename]             ; char *
    push    cs
    call    near ptr load_sfx_ge
    add     sp, 0x6
    mov     word ptr [bp+var_4], ax
    mov     word ptr [bp+var_2], dx
LAB_370d_0ba1:
    mov     ax, word ptr [bp+var_4]
    or      ax, word ptr [bp+var_2]
    jnz     LAB_370d_0bc1
    mov     ax, offset audiodriverstring2
    push    ax                                 ; int
    mov     ax, offset aSfx
    push    ax
    push    word ptr [bp+filename]             ; char *
    push    cs
    call    near ptr load_sfx_ge
    add     sp, 0x6
    mov     word ptr [bp+var_4], ax
    mov     word ptr [bp+var_2], dx
LAB_370d_0bc1:
    mov     ax, word ptr [bp+var_4]
    or      ax, word ptr [bp+var_2]
    jnz     LAB_370d_0bdf
    cmp     word ptr [word_4063C], 0x0
    jz      LAB_370d_0bdf
    push    word ptr [bp+filename]
    mov     ax, offset aCannotLoadSfxFileS
    push    ax
    call    far ptr fatal_error
    add     sp, 0x4
LAB_370d_0bdf:
    mov     ax, word ptr [bp+var_4]
    mov     dx, word ptr [bp+var_2]
    mov     sp, bp
    pop     bp
    retf
load_sfx_file endp
    db 0x90

; void * __cdecl16far load_song_file(char * filename)
load_song_file proc far
    var_4      = word ptr   -4
    var_2      = word ptr   -2
    filename   = word ptr    6

    push    bp
    mov     bp, sp
    sub     sp, 0x4
    sub     ax, ax
    mov     word ptr [bp+var_2], ax
    mov     word ptr [bp+var_4], ax
    mov     ax, offset audiodriverstring2
    push    ax                                 ; int
    mov     ax, offset aKms
    push    ax
    push    word ptr [bp+filename]             ; char *
    push    cs
    call    near ptr load_sfx_ge
    add     sp, 0x6
    mov     word ptr [bp+var_4], ax
    mov     word ptr [bp+var_2], dx
    or      ax, dx
    jnz     LAB_370d_0c2a
    cmp     word ptr [word_4063C], 0x0
    jz      LAB_370d_0c2a
    push    word ptr [bp+filename]
    mov     ax, offset aCannotLoadSongFileS
    push    ax
    call    far ptr fatal_error
    add     sp, 0x4
LAB_370d_0c2a:
    mov     ax, word ptr [bp+var_4]
    mov     dx, word ptr [bp+var_2]
    mov     sp, bp
    pop     bp
    retf
load_song_file endp

; void * __cdecl16far load_voice_file(char * filename)
load_voice_file proc far
    var_4      = word ptr   -4
    var_2      = word ptr   -2
    filename   = word ptr    6

    push    bp
    mov     bp, sp
    sub     sp, 0x4
    sub     ax, ax
    mov     word ptr [bp+var_2], ax
    mov     word ptr [bp+var_4], ax
    cmp     byte ptr [g_auddrv_d], 0x0
    jz      LAB_370d_0c61
    mov     ax, offset audiodriverstring2
    push    ax                                 ; int
    mov     ax, offset aDvc
    push    ax
    push    word ptr [bp+filename]             ; char *
    push    cs
    call    near ptr load_sfx_ge
    add     sp, 0x6
    mov     word ptr [bp+var_4], ax
    mov     word ptr [bp+var_2], dx
LAB_370d_0c61:
    mov     ax, word ptr [bp+var_4]
    or      ax, word ptr [bp+var_2]
    jnz     LAB_370d_0c81
    mov     ax, offset audiodriverstring2
    push    ax                                 ; int
    mov     ax, offset aVce
    push    ax
    push    word ptr [bp+filename]             ; char *
    push    cs
    call    near ptr load_sfx_ge
    add     sp, 0x6
    mov     word ptr [bp+var_4], ax
    mov     word ptr [bp+var_2], dx
LAB_370d_0c81:
    mov     ax, word ptr [bp+var_4]
    or      ax, word ptr [bp+var_2]
    jnz     LAB_370d_0c9f
    cmp     word ptr [word_4063C], 0x0
    jz      LAB_370d_0c9f
    push    word ptr [bp+filename]
    mov     ax, offset aCannotLoadVoiceFileS
    push    ax
    call    far ptr fatal_error
    add     sp, 0x4
LAB_370d_0c9f:
    mov     ax, word ptr [bp+var_4]
    mov     dx, word ptr [bp+var_2]
    mov     sp, bp
    pop     bp
    retf
load_voice_file endp
    db 0x90

; void * __cdecl16far nopsub_load_sample_file(char * filename)
nopsub_load_sample_file proc far
    var_4      = word ptr   -4
    var_2      = word ptr   -2
    filename   = word ptr    6

    push    bp
    mov     bp, sp
    sub     sp, 0x4
    mov     ax, offset audiodriverstring2
    push    ax                                 ; int
    mov     ax, offset aSlb
    push    ax
    push    word ptr [bp+filename]             ; char *
    push    cs
    call    near ptr load_sfx_ge
    add     sp, 0x6
    mov     word ptr [bp+var_4], ax
    mov     word ptr [bp+var_2], dx
    or      ax, dx
    jnz     LAB_370d_0ce2
    cmp     word ptr [word_4063C], 0x0
    jz      LAB_370d_0ce2
    push    word ptr [bp+filename]
    mov     ax, offset aCannotLoadSampleFileS
    push    ax
    call    far ptr fatal_error
    add     sp, 0x4
LAB_370d_0ce2:
    mov     ax, word ptr [bp+var_4]
    mov     dx, word ptr [bp+var_2]
    mov     sp, bp
    pop     bp
    retf
nopsub_load_sample_file endp

; undefined __cdecl16far audio_init_chunk(int param_1, int param_2, int param_3, int param_4, undefined2 param_5, undefined1 param_6, undefined1 param_7)
audio_init_chunk proc far
    var_A      = word ptr  -10
    var_8      = word ptr   -8
    var_6      = word ptr   -6
    var_4      = word ptr   -4
    var_2      = word ptr   -2
    param_1    = word ptr    6
    param_2    = word ptr    8
    param_3    = word ptr   10
    param_4    = word ptr   12
    param_5    = word ptr   14
    param_6    = byte ptr   16
    param_7    = byte ptr   18

    push    bp
    mov     bp, sp
    sub     sp, 0xa
    push    di
    push    si
    mov     ax, word ptr [bp+param_1]
    mov     word ptr [bp+var_6], ax
    mov     ax, word ptr [bp+param_2]
    cmp     word ptr [bp+var_6], ax
    jle     LAB_370d_0d05
    jmp     near ptr LAB_370d_0dea
LAB_370d_0d05:
    mov     ax, 0x4c
    imul    word ptr [bp+param_1]
    add     ax, offset audiochunks_unk
    mov     word ptr [bp+var_A], ax
    mov     di, word ptr [bp+var_6]
LAB_370d_0d14:
    mov     si, word ptr [bp+var_A]
    sub     ax, ax
    mov     word ptr [si+0x4a], ax
    mov     word ptr [si+0x48], ax
    mov     byte ptr [si+0x22], 0x7f
    mov     ax, di
    mov     byte ptr [si+0x23], al
    mov     byte ptr [si+0x16], 0xf
    mov     byte ptr [di+byte_44D06], 0x0
    mov     byte ptr [di+byte_44ACA], 0x0
    mov     byte ptr [si+0x32], 0x0
    mov     byte ptr [si+0x4], 0x0
    mov     al, byte ptr [bp+param_7]
    mov     byte ptr [si+0x24], al
    mov     byte ptr [si+0x15], 0x0
    sub     ax, ax
    mov     word ptr [si+0x1a], ax
    mov     word ptr [si+0x18], ax
    mov     byte ptr [si+0x1c], 0x0
    mov     word ptr [si+0x20], ax
    mov     word ptr [si+0x1e], ax
    mov     al, byte ptr [bp+param_6]
    mov     byte ptr [si+0x28], al
    mov     byte ptr [si+0x25], 0x0
    mov     word ptr [si+0x26], 0x0
    mov     byte ptr [si+0x29], 0x0
    mov     byte ptr [si+0x2a], 0x0
    mov     byte ptr [si+0x2b], 0x0
    mov     byte ptr [si+0x2c], 0x0
    mov     byte ptr [si+0x47], 0xff
    mov     ax, word ptr [bp+param_3]
    or      ax, word ptr [bp+param_4]
    jz      LAB_370d_0dd0
    mov     ax, word ptr [bp+param_5]
    add     ax, word ptr [bp+param_3]
    mov     dx, word ptr [bp+param_4]
    mov     word ptr [bp+var_4], ax
    mov     word ptr [bp+var_2], dx
    push    dx
    push    ax
    push    cs
    call    near ptr audioresource_get_dword
    add     sp, 0x4
    add     ax, 0x4
    mov     word ptr [si+0x5], ax
    mov     word ptr [si+0x7], dx
    push    word ptr [bp+var_2]
    push    word ptr [bp+var_4]
    push    cs
    call    near ptr audioresource_get_dword
    add     sp, 0x4
    add     ax, 0x4
    mov     word ptr [si], ax
    mov     word ptr [si+0x2], dx
    add     word ptr [bp+param_5], 0x5
    mov     ax, word ptr [bp+param_3]
    mov     dx, word ptr [bp+param_4]
    add     ax, 0x7
    mov     word ptr [si+0x2e], ax
    mov     word ptr [si+0x30], dx
    jmp     LAB_370d_0dd7
LAB_370d_0dd0:
    sub     ax, ax
    mov     word ptr [si+0x2], ax
    mov     word ptr [si], ax
LAB_370d_0dd7:
    add     word ptr [bp+var_A], 0x4c
    inc     di
    cmp     di, word ptr [bp+param_2]
    jg      LAB_370d_0de4
    jmp     near ptr LAB_370d_0d14
LAB_370d_0de4:
    mov     word ptr [bp+var_6], di
    mov     word ptr [bp+var_8], si
LAB_370d_0dea:
    pop     si
    pop     di
    mov     sp, bp
    pop     bp
    retf
audio_init_chunk endp

; void __cdecl16far audio_map_song_instruments(void * songdata, void * voicedata)
audio_map_song_instruments proc far
    var_22     = word ptr  -34
    var_20     = word ptr  -32
    var_1E     = word ptr  -30
    var_numsomething = word ptr  -28
    var_1A     = word ptr  -26
    var_hdrptr = dword ptr -22
    var_12     = word ptr  -18
    var_counter = word ptr  -16
    var_E      = word ptr  -14
    var_C      = word ptr  -12
    var_namebuf = byte ptr  -10
    var_6      = byte ptr   -6
    var_4      = word ptr   -4
    var_2      = word ptr   -2
    songdata   = dword ptr   6
    voicedata  = dword ptr  10

    push    bp
    mov     bp, sp
    sub     sp, 0x22
    push    di
    push    si
    mov     byte ptr [bp+var_6], 0x0
    mov     ax, offset aHdr1_0
    push    ax
    push    word ptr [bp+songdata+2]
    push    word ptr [bp+songdata]
    call    far ptr audioresource_find
    add     sp, 0x6
    mov     word ptr [bp+var_hdrptr], ax
    mov     word ptr [bp+var_hdrptr+2], dx
    or      ax, dx
    jnz     LAB_370d_0e1b
    jmp     near ptr LAB_370d_0f66
LAB_370d_0e1b:
    mov     word ptr [bp+var_counter], 0x0
    les     bx, [bp+var_hdrptr]
    mov     al, byte ptr es:[bx+0x6]           ; counter is compared to this - numsomething?
    sub     ah, ah
    or      ax, ax
    jnz     LAB_370d_0e30
    jmp     near ptr LAB_370d_0eb7
LAB_370d_0e30:
    mov     word ptr [bp+var_numsomething], ax
    mov     word ptr [bp+var_1E], 0x0
    mov     ax, bx
    add     ax, 0x7
    mov     word ptr [bp+var_22], ax           ; ax = hdrptr + 7 = instrument names; which are to be replaced with pointers to the instruments in the vce?
    mov     word ptr [bp+var_20], dx
LAB_370d_0e43:
    mov     word ptr [bp+var_12], 0x0
    mov     di, word ptr [bp+var_1E]
    sub     cx, cx
    mov     word ptr [bp+var_1A], ds
    lds     si, [bp+var_hdrptr]
LAB_370d_0e53:
    mov     bx, di
    add     bx, cx
    mov     al, byte ptr [bx+si+0x7]
    mov     bx, cx
    add     bx, bp
    mov     byte ptr ss:[bx+var_namebuf], al
    inc     cx
    cmp     cx, 0x4
    jl      LAB_370d_0e53
    mov     ds, word ptr [bp+var_1A]
    mov     word ptr [bp+var_12], cx
    mov     ax, word ptr [bp+var_22]
    mov     dx, word ptr [bp+var_20]
    mov     word ptr [bp+var_4], ax
    mov     word ptr [bp+var_2], dx
    lea     ax, [bp+var_namebuf]
    push    ax
    push    word ptr [bp+voicedata+2]
    push    word ptr [bp+voicedata]
    call    far ptr audioresource_find
    add     sp, 0x6
    mov     word ptr [bp+var_E], ax
    mov     word ptr [bp+var_C], dx
    lea     ax, [bp+var_E]
    push    ss
    push    ax
    push    word ptr [bp+var_2]
    push    word ptr [bp+var_4]
    push    cs
    call    near ptr audioresource_copy_4_bytes ; looks like it replaces 4-byte names with pointers
    add     sp, 0x8
    add     word ptr [bp+var_1E], 0x4
    add     word ptr [bp+var_22], 0x4
    inc     word ptr [bp+var_counter]
    mov     ax, word ptr [bp+var_numsomething]
    cmp     word ptr [bp+var_counter], ax
    jc      LAB_370d_0e43
LAB_370d_0eb7:
    mov     ax, offset aBasd
    push    ax
    push    word ptr [bp+voicedata+2]
    push    word ptr [bp+voicedata]
    call    far ptr audioresource_find
    add     sp, 0x6
    mov     word ptr [basdres], ax
    mov     word ptr [basdres+2], dx
    mov     ax, offset aSnar
    push    ax
    push    word ptr [bp+voicedata+2]
    push    word ptr [bp+voicedata]
    call    far ptr audioresource_find
    add     sp, 0x6
    mov     word ptr [snarres], ax
    mov     word ptr [snarres+2], dx
    mov     ax, offset aTomm
    push    ax
    push    word ptr [bp+voicedata+2]
    push    word ptr [bp+voicedata]
    call    far ptr audioresource_find
    add     sp, 0x6
    mov     word ptr [tommres], ax
    mov     word ptr [tommres+2], dx
    mov     ax, offset aRide
    push    ax
    push    word ptr [bp+voicedata+2]
    push    word ptr [bp+voicedata]
    call    far ptr audioresource_find
    add     sp, 0x6
    mov     word ptr [rideres], ax
    mov     word ptr [rideres+2], dx
    mov     ax, offset aCrsh
    push    ax
    push    word ptr [bp+voicedata+2]
    push    word ptr [bp+voicedata]
    call    far ptr audioresource_find
    add     sp, 0x6
    mov     word ptr [crshres], ax
    mov     word ptr [crshres+2], dx
    mov     ax, offset aChht
    push    ax
    push    word ptr [bp+voicedata+2]
    push    word ptr [bp+voicedata]
    call    far ptr audioresource_find
    add     sp, 0x6
    mov     word ptr [chhtres], ax
    mov     word ptr [chhtres+2], dx
    mov     ax, offset aOhht
    push    ax
    push    word ptr [bp+voicedata+2]
    push    word ptr [bp+voicedata]
    call    far ptr audioresource_find
    add     sp, 0x6
    mov     word ptr [ohhtres], ax
    mov     word ptr [ohhtres+2], dx
LAB_370d_0f66:
    pop     si
    pop     di
    mov     sp, bp
    pop     bp
    retf
audio_map_song_instruments endp

; undefined __cdecl16far nopsub_3803C(undefined4 param_1, int param_2, int param_3)
nopsub_3803C proc far
    var_22     = word ptr  -34
    var_20     = word ptr  -32
    var_1C     = word ptr  -28
    var_18     = word ptr  -24
    var_16     = word ptr  -22
    var_14     = word ptr  -20
    var_12     = word ptr  -18
    var_10     = word ptr  -16
    var_E      = word ptr  -14
    var_C      = word ptr  -12
    var_A      = byte ptr  -10
    var_4      = dword ptr  -4
    param_1    = dword ptr   6
    param_2    = word ptr   10
    param_3    = word ptr   12

    push    bp
    mov     bp, sp
    sub     sp, 0x22
    push    di
    push    si
    mov     ax, word ptr [bp+param_2]
    or      ax, word ptr [bp+param_3]
    jnz     LAB_370d_0f7f
    jmp     near ptr LAB_370d_107f
LAB_370d_0f7f:
    mov     ax, word ptr [bp+param_1]
    or      ax, word ptr [bp+param_1+2]
    jnz     LAB_370d_0f8a
    jmp     near ptr LAB_370d_107f
LAB_370d_0f8a:
    les     bx, [bp+param_1]
    mov     al, byte ptr es:[bx+0x4]
    sub     ah, ah
    mov     word ptr [bp+var_22], ax
    mov     word ptr [bp+var_14], ax
    mov     word ptr [bp+var_16], 0x0
    or      ax, ax
    jnz     LAB_370d_0fa5
    jmp     near ptr LAB_370d_107f
LAB_370d_0fa5:
    mov     word ptr [bp+var_20], 0x0
LAB_370d_0faa:
    mov     word ptr [bp+var_18], 0x0
    mov     di, word ptr [bp+var_20]
    sub     cx, cx
    mov     word ptr [bp+var_1C], ds
    lds     si, [bp+param_1]
LAB_370d_0fba:
    mov     bx, di
    add     bx, cx
    mov     al, byte ptr [bx+si+0x6]
    mov     bx, cx
    add     bx, bp
    mov     byte ptr ss:[bx+var_A], al
    inc     cx
    cmp     cx, 0x4
    jl      LAB_370d_0fba
    mov     ds, word ptr [bp+var_1C]
    mov     word ptr [bp+var_18], cx
    lea     ax, [bp+var_A]
    push    ax
    push    word ptr [bp+param_1+2]
    push    word ptr [bp+param_1]
    call    far ptr audioresource_find
    add     sp, 0x6
    mov     word ptr [bp+var_4], ax
    mov     word ptr [bp+var_4+2], dx
    les     bx, [bp+var_4]
    cmp     byte ptr es:[bx+0x5], 0x3
    jz      LAB_370d_0ffe
    cmp     byte ptr es:[bx+0x5], 0x6
    jnz     LAB_370d_1067
LAB_370d_0ffe:
    cmp     byte ptr es:[bx+0xa], 0x0
    jnz     LAB_370d_1067
    mov     word ptr [bp+var_18], 0x0
    mov     ax, bx
    mov     dx, es
    add     ax, 0x6
    mov     cx, 0x2
    lea     di, [bp+var_A]
    mov     si, ax
    push    ss
    pop     es
    push    ds
    mov     ds, dx
    rep movsw
    pop     ds
    mov     word ptr [bp+var_18], 0x4
    mov     ax, bx
    add     ax, 0x6
    mov     word ptr [bp+var_E], ax
    mov     word ptr [bp+var_C], dx
    lea     ax, [bp+var_A]
    push    ax
    push    word ptr [bp+param_3]
    push    word ptr [bp+param_2]
    call    far ptr locate_shape_nofatal
    add     sp, 0x6
    mov     word ptr [bp+var_12], ax
    mov     word ptr [bp+var_10], dx
    or      ax, dx
    jz      LAB_370d_1067
    lea     ax, [bp+var_12]
    push    ss
    push    ax
    push    word ptr [bp+var_C]
    push    word ptr [bp+var_E]
    push    cs
    call    near ptr audioresource_copy_4_bytes
    add     sp, 0x8
    les     bx, [bp+var_4]
    mov     byte ptr es:[bx+0xa], 0xff
LAB_370d_1067:
    add     word ptr [bp+var_20], 0x4
    inc     word ptr [bp+var_16]
    les     bx, [bp+param_1]
    mov     al, byte ptr es:[bx+0x4]
    sub     ah, ah
    cmp     ax, word ptr [bp+var_16]
    jbe     LAB_370d_107f
    jmp     near ptr LAB_370d_0faa
LAB_370d_107f:
    pop     si
    pop     di
    mov     sp, bp
    pop     bp
    retf
nopsub_3803C endp
    db 0x90

; void __cdecl16far sub_38156(int param_1)
sub_38156 proc far
    var_2      = word ptr   -2
    param_1    = word ptr    6

    push    bp
    mov     bp, sp
    sub     sp, 0x2
    mov     ax, 0x2e
    imul    word ptr [bp+param_1]
    add     ax, offset unk_45A26
    mov     word ptr [bp+var_2], ax
    mov     bx, ax
    mov     word ptr [bx+0xc], 0x1
    mov     word ptr [bx+0xe], 0x0
    mov     sp, bp
    pop     bp
    retf
sub_38156 endp

; void __cdecl16far sub_38178(void)
sub_38178 proc far
    var_10     = dword ptr -16
    var_C      = word ptr  -12
    var_A      = word ptr  -10
    var_8      = word ptr   -8
    var_6      = word ptr   -6
    var_2      = word ptr   -2

    push    bp
    mov     bp, sp
    sub     sp, 0x10
    push    di
    push    si
    mov     word ptr [word_4063A], 0x1
    sub     ax, ax
    push    ax
    mov     ax, 0x7f
    push    ax
    sub     ax, ax
    push    ax
    push    ax
    push    ax
    mov     ax, 0x17
    push    ax
    sub     ax, ax
    push    ax
    push    cs
    call    near ptr audio_init_chunk
    add     sp, 0xe
    mov     word ptr [bp+var_2], 0x0
    mov     al, byte ptr [byte_459D2]
    sub     ah, ah
    or      ax, ax
    jz      LAB_370d_1151
    mov     di, 0xa2b7
    mov     word ptr [bp+var_6], 0xa2b6
    mov     word ptr [bp+var_8], 0xa2b8
    mov     word ptr [bp+var_A], 0xa2c6
    mov     word ptr [bp+var_C], 0xa2e2
    mov     si, word ptr [bp+var_2]
LAB_370d_10f8:
    push    si
    mov     ax, word ptr [audiodriverbinary]
    mov     dx, word ptr [audiodriverbinary+2]
    add     ax, 0x1e
    mov     word ptr [bp+var_10+2], dx
    mov     word ptr [bp+var_10], ax
    call    dword ptr [bp+var_10]
    add     sp, 0x2
    mov     byte ptr [di], 0x0
    mov     bx, word ptr [bp+var_6]
    mov     byte ptr [bx], 0xff
    mov     bx, word ptr [bp+var_8]
    mov     byte ptr [bx], 0x0
    mov     bx, word ptr [bp+var_A]
    sub     ax, ax
    mov     word ptr [bx+0x2], ax
    mov     word ptr [bx], ax
    mov     bx, word ptr [bp+var_C]
    mov     byte ptr [bx], 0xff
    add     di, 0x2e
    add     word ptr [bp+var_6], 0x2e
    add     word ptr [bp+var_8], 0x2e
    add     word ptr [bp+var_A], 0x2e
    add     word ptr [bp+var_C], 0x2e
    inc     si
    mov     ax, si
    mov     cl, byte ptr [byte_459D2]
    sub     ch, ch
    cmp     ax, cx
    jc      LAB_370d_10f8
    mov     word ptr [bp+var_2], si
LAB_370d_1151:
    mov     ax, word ptr [audiodriverbinary]
    mov     dx, word ptr [audiodriverbinary+2]
    add     ax, 0x18
    mov     word ptr [bp+var_10+2], dx
    mov     word ptr [bp+var_10], ax
    call    dword ptr [bp+var_10]
    mov     ax, word ptr [audiodriverbinary]
    mov     dx, word ptr [audiodriverbinary+2]
    add     ax, 0x6
    mov     word ptr [bp+var_10+2], dx
    mov     word ptr [bp+var_10], ax
    call    dword ptr [bp+var_10]
    mov     word ptr [word_4063A], 0x0
    pop     si
    pop     di
    mov     sp, bp
    pop     bp
    retf
sub_38178 endp
    db 0x90

; void __cdecl16far audio_map_song_tracks(void * songchunk)
audio_map_song_tracks proc far
    var_counter_shl2 = word ptr  -50
    var_30     = word ptr  -48
    var_2E     = word ptr  -46
    var_2C     = word ptr  -44
    var_counter = word ptr  -42
    var_chunknamesofs = word ptr  -40
    var_chunknamesseg = word ptr  -38
    var_24     = byte ptr  -36
    var_firstchunkdataofs = word ptr  -34
    var_firstchunkdataseg = word ptr  -32
    var_1E     = word ptr  -30
    var_1C     = word ptr  -28
    var_1A     = word ptr  -26
    var_18     = word ptr  -24
    var_numchunks = word ptr  -22
    var_14     = dword ptr -20
    var_10     = word ptr  -16
    var_E      = word ptr  -14
    var_namebuf = byte ptr  -12
    var_8      = byte ptr   -8
    var_chunkofsofs = word ptr   -6
    var_chunkofsseg = word ptr   -4
    var_2      = byte ptr   -2
    songchunk  = dword ptr   6

    push    bp
    mov     bp, sp
    sub     sp, 0x32
    push    di
    push    si
    mov     byte ptr [bp+var_8], 0x0
    mov     ax, word ptr [bp+songchunk]
    mov     dx, word ptr [bp+songchunk+2]
    add     ax, 0x4
    push    dx
    push    ax
    push    cs
    call    near ptr audioresource_get_word
    add     sp, 0x4
    mov     word ptr [bp+var_numchunks], ax
    mov     ax, word ptr [bp+songchunk]
    mov     dx, word ptr [bp+songchunk+2]
    add     ax, 0x6
    mov     word ptr [bp+var_chunknamesofs], ax
    mov     word ptr [bp+var_chunknamesseg], dx
    mov     ax, word ptr [bp+var_numchunks]
    shl     ax, 0x1
    shl     ax, 0x1
    add     ax, word ptr [bp+var_chunknamesofs]
    mov     word ptr [bp+var_chunkofsofs], ax
    mov     word ptr [bp+var_chunkofsseg], dx
    mov     ax, word ptr [bp+var_numchunks]
    mov     cl, 0x3
    shl     ax, cl
    add     ax, word ptr [bp+songchunk]
    add     ax, 0x6
    mov     word ptr [bp+var_firstchunkdataofs], ax
    mov     word ptr [bp+var_firstchunkdataseg], dx
    mov     word ptr [bp+var_counter], 0x0
    jmp     near ptr LAB_370d_12f9
    db 0x90
LAB_370d_11e0:
    inc     word ptr [bp+var_14]
LAB_370d_11e3:
    les     bx, [bp+var_14]
    test    byte ptr es:[bx], 0x80
    jnz     LAB_370d_11e0
    inc     word ptr [bp+var_14]
    mov     bx, word ptr [bp+var_14]
    mov     al, byte ptr es:[bx]
    sub     ah, ah
    sub     ax, 0xd9
    cmp     ax, 0x11
    jbe     LAB_370d_1202
    jmp     near ptr LAB_370d_12ae
LAB_370d_1202:
    add     ax, ax
    xchg    ax, bx
switchD:
    jmp     word ptr cs:[bx+off_383A0]
LAB_370d_120a:
    add     word ptr [bp-0x14], 0x2
    mov     ax, 0x4
    push    ax
    lea     ax, [bp-0xc]
    push    ss
    push    ax
    push    es
    push    word ptr [bp-0x14]
    call    far ptr audioresource_copy_n_bytes
    add     sp, 0xa
    push    word ptr [bp-0x26]
    push    word ptr [bp-0x28]
    lea     ax, [bp-0xc]
    push    ax
    push    word ptr [bp-0x16]
    sub     ax, ax
    push    ax
    call    far ptr audioresource_get_chunk_index
    add     sp, 0xa
    mov     word ptr [bp-0x2e], ax
    cmp     ax, 0xffff
    jz      LAB_370d_127a
    shl     ax, 0x1
    shl     ax, 0x1
    add     ax, word ptr [bp-0x6]
    mov     dx, word ptr [bp-0x4]
    push    dx
    push    ax
    push    cs
    call    near ptr audioresource_get_dword
    add     sp, 0x4
    mov     word ptr [bp-0x1e], ax
    mov     word ptr [bp-0x1c], dx
    add     ax, word ptr [bp-0x22]
    mov     dx, word ptr [bp-0x20]
    mov     word ptr [bp-0x10], ax
    mov     word ptr [bp-0xe], dx
    lea     ax, [bp-0x10]
    push    ss
    push    ax
    push    word ptr [bp-0x12]
    push    word ptr [bp-0x14]
    push    cs
    call    near ptr audioresource_copy_4_bytes
    add     sp, 0x8
LAB_370d_127a:
    add     word ptr [bp-0x14], 0x4
_parse_trackdata:
    mov     ax, word ptr [bp+var_1A]
    mov     dx, word ptr [bp+var_18]
    cmp     word ptr [bp+var_14], ax
    jnc     LAB_370d_12f6
    jmp     near ptr LAB_370d_11e3
LAB_370d_128c:
    add     word ptr [bp-0x14], 0x2
    jmp     _parse_trackdata
LAB_370d_1292:
    add     word ptr [bp-0x14], 0x3
    jmp     _parse_trackdata
LAB_370d_1298:
    inc     word ptr [bp-0x14]
    les     bx, [bp-0x14]
    inc     word ptr [bp-0x14]
    mov     al, byte ptr es:[bx]
    mov     byte ptr [bp-0x2], al
    sub     ah, ah
    add     word ptr [bp-0x14], ax
    jmp     _parse_trackdata
LAB_370d_12ae:
    mov     bx, word ptr [bp+var_14]
    mov     al, byte ptr es:[bx]
    sub     ah, ah
    cmp     ax, 0x80
    jc      LAB_370d_12be
    inc     word ptr [bp+var_14]
LAB_370d_12be:
    inc     word ptr [bp+var_14]
    mov     bx, word ptr [bp+var_14]
    test    byte ptr es:[bx], 0x80
    jnz     LAB_370d_12be
_trkdata_case0_1_2_10:
    inc     word ptr [bp+var_14]
    jmp     _parse_trackdata
    db 0x90
off_383A0:
    dw _trkdata_case0_1_2_10
    dw _trkdata_case0_1_2_10
    dw _trkdata_case0_1_2_10
    dw LAB_370d_128c
    dw LAB_370d_128c
    dw LAB_370d_128c
    dw LAB_370d_1292
    dw LAB_370d_128c
    dw LAB_370d_128c
    dw LAB_370d_128c
    dw _trkdata_case0_1_2_10
    dw LAB_370d_128c
    dw LAB_370d_1292
    dw LAB_370d_120a
    dw LAB_370d_1298
    dw LAB_370d_1298
    dw LAB_370d_128c
    dw LAB_370d_128c
    jmp     _parse_trackdata
LAB_370d_12f6:
    inc     word ptr [bp+var_counter]
LAB_370d_12f9:
    mov     ax, word ptr [bp+var_numchunks]
    cmp     word ptr [bp+var_counter], ax
    jl      LAB_370d_1304
    jmp     near ptr LAB_370d_1424
LAB_370d_1304:
    mov     ax, word ptr [bp+var_counter]
    shl     ax, 0x1
    shl     ax, 0x1
    mov     word ptr [bp+var_counter_shl2], ax
    add     ax, word ptr [bp+var_chunkofsofs]
    mov     dx, word ptr [bp+var_chunkofsseg]
    push    dx
    push    ax
    push    cs
    call    near ptr audioresource_get_dword
    add     sp, 0x4
    add     ax, word ptr [bp+var_firstchunkdataofs]
    mov     dx, word ptr [bp+var_firstchunkdataseg]
    mov     word ptr [bp+var_14], ax
    mov     word ptr [bp+var_14+2], dx
    lea     ax, [bp+var_14]
    push    ss
    push    ax
    push    cs
    call    near ptr audioresource_get_dword
    add     sp, 0x4
    add     ax, word ptr [bp+var_14]
    mov     dx, word ptr [bp+var_14+2]
    mov     word ptr [bp+var_1A], ax
    mov     word ptr [bp+var_18], dx
    add     word ptr [bp+var_14], 0x4
    mov     ax, 0x4
    push    ax
    mov     ax, offset aHdr1_1
    push    ds
    push    ax
    mov     ax, word ptr [bp+var_counter_shl2]
    add     ax, word ptr [bp+var_chunknamesofs]
    mov     dx, word ptr [bp+var_chunknamesseg]
    push    dx
    push    ax
    sub     ax, ax
    push    ax
    call    far ptr audioresource_compare_chunknames
    add     sp, 0xc
    or      ax, ax                             ; ax = 1, found hdr1 at the counter index
    jnz     _patch_hdrdata_trackptrs
    jmp     near ptr _parse_trackdata
_patch_hdrdata_trackptrs:
    add     word ptr [bp+var_14], 0x2
    les     bx, [bp+var_14]
    mov     al, byte ptr es:[bx]
    mov     byte ptr [bp+var_24], al
    sub     ah, ah
    shl     ax, 0x1
    shl     ax, 0x1
    inc     ax
    add     word ptr [bp+var_14], ax
    mov     bx, word ptr [bp+var_14]
    mov     al, byte ptr es:[bx]
    mov     byte ptr [bp+var_24], al
    inc     word ptr [bp+var_14]
    mov     word ptr [bp+var_2C], 0x0
    sub     ah, ah
    or      ax, ax
    jnz     LAB_370d_139c
    jmp     near ptr LAB_370d_12f6
LAB_370d_139c:
    mov     word ptr [bp+var_30], ax
    mov     di, word ptr [bp+var_2C]
LAB_370d_13a2:
    mov     ax, 0x4
    push    ax
    lea     ax, [bp+var_namebuf]
    push    ss
    push    ax
    push    word ptr [bp+var_14+2]
    push    word ptr [bp+var_14]
    call    far ptr audioresource_copy_n_bytes
    add     sp, 0xa
    push    word ptr [bp+var_chunknamesseg]
    push    word ptr [bp+var_chunknamesofs]
    lea     ax, [bp+var_namebuf]
    push    ax
    push    word ptr [bp+var_numchunks]
    sub     ax, ax
    push    ax
    call    far ptr audioresource_get_chunk_index
    add     sp, 0xa
    mov     si, ax
    cmp     si, -0x1
    jz      LAB_370d_140f
    shl     ax, 0x1
    shl     ax, 0x1
    add     ax, word ptr [bp+var_chunkofsofs]
    mov     dx, word ptr [bp+var_chunkofsseg]
    push    dx
    push    ax
    push    cs
    call    near ptr audioresource_get_dword
    add     sp, 0x4
    mov     word ptr [bp+var_1E], ax
    mov     word ptr [bp+var_1C], dx
    add     ax, word ptr [bp+var_firstchunkdataofs]
    mov     dx, word ptr [bp+var_firstchunkdataseg]
    mov     word ptr [bp+var_10], ax
    mov     word ptr [bp+var_E], dx
    lea     ax, [bp+var_10]
    push    ss
    push    ax
    push    word ptr [bp+var_14+2]
    push    word ptr [bp+var_14]
    push    cs
    call    near ptr audioresource_copy_4_bytes
    add     sp, 0x8
LAB_370d_140f:
    add     word ptr [bp+var_14], 0x5
    inc     di
    mov     ax, di
    cmp     ax, word ptr [bp+var_30]
    jc      LAB_370d_13a2
    mov     word ptr [bp+var_2C], di
    mov     word ptr [bp+var_2E], si
    jmp     near ptr LAB_370d_12f6
LAB_370d_1424:
    pop     si
    pop     di
    mov     sp, bp
    pop     bp
    retf
audio_map_song_tracks endp

; dword __cdecl16far audioresource_get_dword(void * data)
audioresource_get_dword proc far
    var_4      = word ptr   -4
    var_2      = word ptr   -2
    data       = dword ptr  10

    push    bp
    mov     bp, sp
    sub     sp, 0x4
    les     bx, [bp+0x6]
    mov     ax, word ptr es:[bx]
    mov     dx, word ptr es:[bx+0x2]
    mov     word ptr [bp+var_4], ax
    mov     word ptr [bp+var_2], dx
    mov     sp, bp
    pop     bp
    retf
audioresource_get_dword endp

; word __cdecl16far audioresource_get_word(void * data)
audioresource_get_word proc far
    var_2      = word ptr   -2
    data       = dword ptr   6

    push    bp
    mov     bp, sp
    sub     sp, 0x2
    les     bx, [bp+data]
    mov     ax, word ptr es:[bx]
    mov     word ptr [bp+var_2], ax
    mov     sp, bp
    pop     bp
    retf
audioresource_get_word endp
    db 0x90

; void __cdecl16far audioresource_copy_4_bytes(void * data_src, void * data_dst)
audioresource_copy_4_bytes proc far
    data_src   = dword ptr   6
    data_dst   = dword ptr  10

    push    bp
    mov     bp, sp
    les     bx, [bp+data_dst]
    inc     word ptr [bp+data_dst]
    mov     al, byte ptr es:[bx]
    les     bx, [bp+data_src]
    inc     word ptr [bp+data_src]
    mov     byte ptr es:[bx], al
    les     bx, [bp+data_dst]
    inc     word ptr [bp+data_dst]
    mov     al, byte ptr es:[bx]
    les     bx, [bp+data_src]
    inc     word ptr [bp+data_src]
    mov     byte ptr es:[bx], al
    les     bx, [bp+data_dst]
    inc     word ptr [bp+data_dst]
    mov     al, byte ptr es:[bx]
    les     bx, [bp+data_src]
    inc     word ptr [bp+data_src]
    mov     byte ptr es:[bx], al
    les     bx, [bp+data_dst]
    mov     al, byte ptr es:[bx]
    les     bx, [bp+data_src]
    mov     byte ptr es:[bx], al
    pop     bp
    retf
audioresource_copy_4_bytes endp
    db 0x90

; undefined __cdecl16far nopsub_debug_music(void)
nopsub_debug_music proc far
    local_a    = word ptr   -8
    local_8    = word ptr   -6
    local_6    = word ptr   -4
    local_4    = word ptr   -2

    push    bp
    mov     bp, sp
    sub     sp, 0x8
    push    di
    push    si
    mov     al, byte ptr [audioflag6]
    sub     ah, ah
    push    ax
    mov     al, byte ptr [byte_40632]
    push    ax
    mov     al, byte ptr [audioflag2]
    push    ax
    mov     al, byte ptr [byte_40630]
    push    ax
    mov     ax, 0x4fa3
    push    ax
    call    far ptr nopsub_debug_print
    add     sp, 0xa
    mov     al, byte ptr [byte_45948]
    sub     ah, ah
    push    ax
    mov     al, byte ptr [byte_45950]
    push    ax
    mov     ax, 0x4fd5
    push    ax
    call    far ptr nopsub_debug_print
    add     sp, 0x6
    sub     si, si
    mov     di, 0x8214
    mov     word ptr [bp+local_8], 0x81fc
LAB_370d_14e6:
    push    word ptr [di+0x2]
    push    word ptr [di]
    mov     bx, word ptr [bp+local_8]
    push    word ptr [bx+0x2]
    push    word ptr [bx]
    push    si
    mov     ax, 0x4ffb
    push    ax
    call    far ptr nopsub_debug_print
    add     sp, 0xc
    add     di, 0x4c
    add     word ptr [bp+local_8], 0x4c
    inc     si
    cmp     si, 0x18
    jl      LAB_370d_14e6
    mov     word ptr [bp+local_4], si
    mov     ax, 0x5010
    push    ax
    call    far ptr nopsub_debug_print
    add     sp, 0x2
    call    far ptr flush_stdin
    sub     si, si
    mov     di, 0xa2c2
    mov     word ptr [bp+local_6], 0xa2be
    mov     word ptr [bp+local_a], 0xa2b7
LAB_370d_1530:
    push    word ptr [di+0x2]
    push    word ptr [di]
    mov     bx, word ptr [bp+local_6]
    push    word ptr [bx+0x2]
    push    word ptr [bx]
    mov     bx, word ptr [bp+local_a]
    mov     al, byte ptr [bx]
    sub     ah, ah
    push    ax
    push    si
    mov     ax, 0x501d
    push    ax
    call    far ptr nopsub_debug_print
    add     sp, 0xe
    add     di, 0x2e
    add     word ptr [bp+local_6], 0x2e
    add     word ptr [bp+local_a], 0x2e
    inc     si
    cmp     si, 0x10
    jl      LAB_370d_1530
    mov     word ptr [bp+local_4], si
    pop     si
    pop     di
    mov     sp, bp
    pop     bp
    retf
nopsub_debug_music endp

seg027 ends
end
