; Generated by restunts-export.py (Ghidra)
.8086
.model medium

include seg011.inc

seg011 segment byte public use16 'STUNTSC'
    assume cs:seg011, es:nothing, ss:nothing, ds:dseg

    db 0

; ******************************************************************************
; * int3dhypot
; ******************************************************************************

; int __cdecl16far int_hypot_3d(VECTOR * vec)
int_hypot_3d_asm_ proc far
    vec        = word ptr    6

    push    bp
    mov     bp, sp
    mov     bx, word ptr [bp+vec]
    push    word ptr [bx+0x4]
    push    word ptr [bx+0x2]
    push    word ptr [bx]
    call    far ptr int_hypot
    add     sp, 0x4
    push    ax
    call    far ptr int_hypot
    add     sp, 0x4
    pop     bp
    retf
int_hypot_3d_asm_ endp

seg011 ends
end
