; Generated by restunts-export.py (Ghidra)
.8086
.model medium

include custom.inc
include structs.inc
include seg000.inc
include seg001.inc
include seg002.inc
include seg003.inc
include seg004.inc
include seg005.inc
include seg006.inc
include seg007.inc
include seg008.inc
include seg009.inc
include seg010.inc
include seg011.inc
include seg012.inc
include seg013.inc
include seg014.inc
include seg015.inc
include seg016.inc
include seg017.inc
include seg018.inc
include seg019.inc
include seg020.inc
include seg021.inc
include seg022.inc
include seg023.inc
include seg024.inc
include seg025.inc
include seg026.inc
include seg027.inc
include seg028.inc
include seg029.inc
include seg031.inc
include seg032.inc
include seg033.inc
include seg034.inc
include seg035.inc
include seg036.inc
include seg037.inc
include seg038.inc
include seg039.inc
include dseg.inc
include dsegu.inc

seg030 segment byte public use16 'STUNTSC'
    assume cs:seg030, es:nothing, ss:nothing, ds:dseg

    public audio_make_filename

    db 2 dup (0x90)
    db 2 dup (0x00)

; char * __cdecl16far audio_make_filename(char * filename, char * extension, char * audiodriver)
audio_make_filename proc far
    var_2      = word ptr   -2
    filename   = word ptr    6
    extension  = word ptr    8
    audiodriver = word ptr   10

    push    bp
    mov     bp, sp
    sub     sp, 0x2
    push    di
    push    si
    mov     si, offset audio_filetemp
    push    ds
    pop     es
    mov     di, word ptr [bp+filename]
    mov     cx, 0xffff
    xor     ax, ax
    repne scasb
    not     cx
    sub     di, cx
    xchg    si, di
    shr     cx, 0x1
    rep movsw
    adc     cx, cx
    rep movsb
    mov     ax, 0x5c
    push    ax
    mov     ax, offset audio_filetemp
    push    ax                                 ; char *
    call    far ptr _strrchr
    add     sp, 0x4
    mov     word ptr [bp+var_2], ax
    or      ax, ax
    jz      LAB_39cc_0056
    inc     word ptr [bp+var_2]
    mov     bx, word ptr [bp+var_2]
    mov     byte ptr [bx], 0x0
    jmp     LAB_39cc_005b
    db 0x90
LAB_39cc_0056:
    mov     byte ptr [audio_filetemp], 0x0
LAB_39cc_005b:
    mov     si, offset audio_filetemp
    push    ds
    pop     es
    mov     di, word ptr [bp+audiodriver]
    mov     cx, 0xffff
    xor     ax, ax
    repne scasb
    not     cx
    sub     di, cx
    mov     bx, cx
    xchg    si, di
    mov     cx, 0xffff
    repne scasb
    dec     di
    mov     cx, bx
    shr     cx, 0x1
    rep movsw
    adc     cx, cx
    rep movsb
    mov     ax, 0x5c
    push    ax
    push    word ptr [bp+filename]             ; char *
    call    far ptr _strrchr
    add     sp, 0x4
    mov     word ptr [bp+var_2], ax
    or      ax, ax
    jz      LAB_39cc_00aa
    inc     word ptr [bp+var_2]
    mov     bx, word ptr [bp+var_2]
    mov     di, bx
    mov     si, offset audio_filetemp
    mov     ax, ds
    mov     es, ax
    jmp     LAB_39cc_00b2
    db 0x90
LAB_39cc_00aa:
    mov     si, offset audio_filetemp
    push    ds
    pop     es
    mov     di, word ptr [bp+filename]
LAB_39cc_00b2:
    mov     cx, 0xffff
    xor     ax, ax
    repne scasb
    not     cx
    sub     di, cx
    mov     bx, cx
    xchg    si, di
    mov     cx, 0xffff
    repne scasb
    dec     di
    mov     cx, bx
    shr     cx, 0x1
    rep movsw
    adc     cx, cx
    rep movsb
    mov     di, offset audio_filetemp
    mov     ax, ds
    mov     es, ax
    mov     cx, 0xffff
    xor     ax, ax
    repne scasb
    not     cx
    dec     cx
    mov     bx, cx
    cmp     byte ptr [bx+byte_42D2A], 0x2e
    jnz     LAB_39cc_00ff
    mov     di, offset audio_filetemp
    mov     ax, ds
    mov     cx, 0xffff
    xor     ax, ax
    repne scasb
    not     cx
    dec     cx
    cmp     cx, 0x4
    ja      LAB_39cc_014b
LAB_39cc_00ff:
    mov     di, offset unk_407AC
    mov     si, offset audio_filetemp
    mov     ax, ds
    mov     cx, 0xffff
    xor     ax, ax
    repne scasb
    not     cx
    sub     di, cx
    mov     bx, cx
    xchg    si, di
    mov     cx, 0xffff
    repne scasb
    dec     di
    mov     cx, bx
    shr     cx, 0x1
    rep movsw
    adc     cx, cx
    rep movsb
    mov     si, offset audio_filetemp
    mov     di, word ptr [bp+extension]
    mov     cx, 0xffff
    xor     ax, ax
    repne scasb
    not     cx
    sub     di, cx
    mov     bx, cx
    xchg    si, di
    mov     cx, 0xffff
    repne scasb
    dec     di
    mov     cx, bx
    shr     cx, 0x1
    rep movsw
    adc     cx, cx
    rep movsb
LAB_39cc_014b:
    mov     ax, offset audio_filetemp
    pop     si
    pop     di
    mov     sp, bp
    pop     bp
    retf
audio_make_filename endp

seg030 ends
end
