; Generated by restunts-export.py (Ghidra)
.8086
.model medium

include custom.inc
include structs.inc
include seg000.inc
include seg001.inc
include seg002.inc
include seg003.inc
include seg004.inc
include seg005.inc
include seg006.inc
include seg007.inc
include seg008.inc
include seg009.inc
include seg010.inc
include seg011.inc
include seg012.inc
include seg013.inc
include seg014.inc
include seg015.inc
include seg016.inc
include seg017.inc
include seg018.inc
include seg019.inc
include seg020.inc
include seg021.inc
include seg022.inc
include seg023.inc
include seg024.inc
include seg025.inc
include seg027.inc
include seg028.inc
include seg029.inc
include seg030.inc
include seg031.inc
include seg032.inc
include seg033.inc
include seg034.inc
include seg035.inc
include seg036.inc
include seg037.inc
include seg038.inc
include seg039.inc
include dseg.inc
include dsegu.inc

seg026 segment byte public use16 'STUNTSC'
    assume cs:seg026, es:nothing, ss:nothing, ds:dseg

    public toupper

; int __cdecl16far toupper(int __ch)
toupper proc far
    __ch       = word ptr    6

    push    bp
    mov     bp, sp
    cmp     word ptr [bp+__ch], 0x61
    jl      LAB_370b_001d
    cmp     word ptr [bp+__ch], 0x7a
    jg      LAB_370b_001d
    sub     word ptr [bp+__ch], 0x20
LAB_370b_001d:
    mov     ax, word ptr [bp+__ch]
    pop     bp
    retf
toupper endp

seg026 ends
end
