; Generated by restunts-export.py (Ghidra)
.8086
.model medium

include custom.inc
include structs.inc
include seg000.inc
include seg001.inc
include seg002.inc
include seg003.inc
include seg004.inc
include seg005.inc
include seg006.inc
include seg007.inc
include seg008.inc
include seg009.inc
include seg010.inc
include seg011.inc
include seg012.inc
include seg013.inc
include seg014.inc
include seg015.inc
include seg016.inc
include seg017.inc
include seg018.inc
include seg019.inc
include seg020.inc
include seg021.inc
include seg022.inc
include seg023.inc
include seg024.inc
include seg025.inc
include seg026.inc
include seg027.inc
include seg028.inc
include seg029.inc
include seg030.inc
include seg031.inc
include seg032.inc
include seg034.inc
include seg035.inc
include seg036.inc
include seg037.inc
include seg038.inc
include seg039.inc
include dseg.inc
include dsegu.inc

seg033 segment byte public use16 'STUNTSC'
    assume cs:seg033, es:nothing, ss:nothing, ds:dseg

    public setup_mcgawnd1
    public setup_mcgawnd2

; void __cdecl16far setup_mcgawnd1(void)
setup_mcgawnd1 proc far
    mov     ax, word ptr [mcgawndsprite]
    or      ax, word ptr [mcgawndsprite+2]
    jnz     LAB_3a95_002c
    mov     ax, 0xf
    push    ax
    mov     ax, 0xc8
    push    ax
    mov     ax, 0x140
    push    ax
    call    far ptr sprite_make_wnd
    add     sp, 0x6
    mov     word ptr [mcgawndsprite], ax
    mov     word ptr [mcgawndsprite+2], dx
LAB_3a95_002c:
    mov     ax, offset sprite2
; <REPLACE>
    mov     dx, seg seg012
; </REPLACE>
;    mov     dx, 0x2ea2
    push    dx
    push    ax
    call    far ptr sprite_set_1_from_argptr
    add     sp, 0x4
    les     bx, [mcgawndsprite]
    push    word ptr es:[bx+0x2]
    push    word ptr es:[bx]
    call    far ptr sprite_putimage
    add     sp, 0x4
    retf
setup_mcgawnd1 endp

; void __cdecl16far setup_mcgawnd2(void)
setup_mcgawnd2 proc far
    mov     ax, word ptr [mcgawndsprite]
    or      ax, word ptr [mcgawndsprite+2]
    jnz     LAB_3a95_0074
    mov     ax, 0xf
    push    ax
    mov     ax, 0xc8
    push    ax
    mov     ax, 0x140
    push    ax
    call    far ptr sprite_make_wnd
    add     sp, 0x6
    mov     word ptr [mcgawndsprite], ax
    mov     word ptr [mcgawndsprite+2], dx
LAB_3a95_0074:
    push    word ptr [mcgawndsprite+2]
    push    word ptr [mcgawndsprite]
    call    far ptr sprite_set_1_from_argptr
    add     sp, 0x4
    retf
setup_mcgawnd2 endp

seg033 ends
end
