; Generated by restunts-export.py (Ghidra)
.8086
.model medium

include custom.inc
include structs.inc
include seg000.inc
include seg001.inc
include seg002.inc
include seg003.inc
include seg004.inc
include seg005.inc
include seg006.inc
include seg007.inc
include seg008.inc
include seg009.inc
include seg010.inc
include seg011.inc
include seg012.inc
include seg014.inc
include seg015.inc
include seg016.inc
include seg017.inc
include seg018.inc
include seg019.inc
include seg020.inc
include seg021.inc
include seg022.inc
include seg023.inc
include seg024.inc
include seg025.inc
include seg026.inc
include seg027.inc
include seg028.inc
include seg029.inc
include seg030.inc
include seg031.inc
include seg032.inc
include seg033.inc
include seg034.inc
include seg035.inc
include seg036.inc
include seg037.inc
include seg038.inc
include seg039.inc
include dseg.inc
include dsegu.inc

seg013 segment byte public use16 'STUNTSC'
    assume cs:seg013, es:nothing, ss:nothing, ds:dseg

    public sprite_1_unk4

; void __cdecl16far sprite_1_unk4(int x1_, int y1_, int x2_, int y2_, uint colour)
sprite_1_unk4 proc far
    var_4      = word ptr   -4
    var_2      = word ptr   -2
    x1_        = word ptr    6
    y1_        = word ptr    8
    x2_        = word ptr   10
    y2_        = word ptr   12
    colour     = word ptr   14

    push    bp
    mov     bp, sp
    sub     sp, 0x4
    mov     ax, word ptr [bp+x2_]
    sub     ax, word ptr [bp+x1_]
    inc     ax
    mov     word ptr [bp+var_2], ax
    mov     ax, word ptr [bp+y2_]
    sub     ax, word ptr [bp+y1_]
    mov     word ptr [bp+var_4], ax
    cmp     word ptr [bp+var_2], 0x0
    jle     LAB_361b_005b
    push    word ptr [bp+colour]
    mov     ax, 0x1
    push    ax
    push    word ptr [bp+var_2]
    push    word ptr [bp+y1_]
    push    word ptr [bp+x1_]
    call    far ptr sprite_1_unk2
    add     sp, 0xa
    push    word ptr [bp+colour]
    mov     ax, 0x1
    push    ax
    push    word ptr [bp+var_2]
    push    word ptr [bp+y2_]
    push    word ptr [bp+x1_]
    call    far ptr sprite_1_unk2
    add     sp, 0xa
LAB_361b_005b:
    cmp     word ptr [bp+var_4], 0x0
    jle     LAB_361b_0091
    push    word ptr [bp+colour]
    push    word ptr [bp+var_4]
    mov     ax, 0x1
    push    ax
    push    word ptr [bp+y1_]
    push    word ptr [bp+x1_]
    call    far ptr sprite_1_unk2
    add     sp, 0xa
    push    word ptr [bp+colour]
    push    word ptr [bp+var_4]
    mov     ax, 0x1
    push    ax
    push    word ptr [bp+y1_]
    push    word ptr [bp+x2_]
    call    far ptr sprite_1_unk2
    add     sp, 0xa
LAB_361b_0091:
    mov     sp, bp
    pop     bp
    retf
sprite_1_unk4 endp

seg013 ends
end
