; Generated by restunts-export.py (Ghidra)
.8086
.model medium

include custom.inc
include structs.inc
include seg000.inc
include seg001.inc
include seg002.inc
include seg003.inc
include seg004.inc
include seg005.inc
include seg006.inc
include seg007.inc
include seg008.inc
include seg009.inc
include seg010.inc
include seg011.inc
include seg012.inc
include seg013.inc
include seg014.inc
include seg015.inc
include seg016.inc
include seg017.inc
include seg018.inc
include seg019.inc
include seg020.inc
include seg021.inc
include seg023.inc
include seg024.inc
include seg025.inc
include seg026.inc
include seg027.inc
include seg028.inc
include seg029.inc
include seg030.inc
include seg031.inc
include seg032.inc
include seg033.inc
include seg034.inc
include seg035.inc
include seg036.inc
include seg037.inc
include seg038.inc
include seg039.inc
include dseg.inc
include dsegu.inc

seg022 segment byte public use16 'STUNTSC'
    assume cs:seg022, es:nothing, ss:nothing, ds:dseg

    public preRender_wheel

; void __cdecl16far preRender_wheel(POINT2D * vertlines, int param_2, uint colour, undefined2 param_4, undefined2 param_5)
preRender_wheel proc far
    var_11A    = word ptr  -282
    var_118    = word ptr  -280
    var_116    = word ptr  -278
    var_114    = word ptr  -276
    var_112    = word ptr  -274
    var_110    = word ptr  -272
    vertlines_arr = dword ptr -270
    var_D2     = byte ptr  -210
    var_CE     = byte ptr  -206
    var_92     = byte ptr  -146
    var_8E     = word ptr  -142
    var_8C     = word ptr  -140
    var_4E     = byte ptr  -78
    var_A      = byte ptr  -10
    var_6      = word ptr   -6
    var_4      = word ptr   -4
    vertlines_ptr = word ptr   -2
    vertlines  = word ptr    6
    param_2    = word ptr    8
    colour     = word ptr   10
    param_4    = word ptr   12
    param_5    = word ptr   14

    push    bp
    mov     bp, sp
    sub     sp, 0x11a
    push    si
    push    word ptr [bp+param_2]
    lea     ax, [bp+vertlines_arr]
    push    ax
    push    word ptr [bp+vertlines]
    call    far ptr preRender_wheel_helper
    add     sp, 0x6
    lea     ax, [bp+vertlines_arr]
    mov     word ptr [bp+vertlines_ptr], ax
    mov     word ptr [bp+var_110], 0x0
LAB_36c7_0036:
    mov     bx, word ptr [bp+vertlines_ptr]
    push    word ptr [bx+0x82]
    push    word ptr [bx+0x80]
    push    word ptr [bx+0x86]
    push    word ptr [bx+0x84]
    push    word ptr [bx+0x6]
    push    word ptr [bx+0x4]
    push    word ptr [bx+0x2]
    push    word ptr [bx]
    mov     ax, 0x4
    push    ax
    push    word ptr [bp+colour]
    call    far ptr preRender_wheel_helper4
    add     sp, 0x14
    add     word ptr [bp+vertlines_ptr], 0x4
    inc     word ptr [bp+var_110]
    cmp     word ptr [bp+var_110], 0xf
    jl      LAB_36c7_0036
    mov     bx, word ptr [bp+vertlines_ptr]
    push    word ptr [bx+0x82]
    push    word ptr [bx+0x80]
    push    word ptr [bp+var_8C]
    push    word ptr [bp+var_8E]
    push    word ptr [bp+vertlines_arr+2]
    push    word ptr [bp+vertlines_arr]
    push    word ptr [bx+0x2]
    push    word ptr [bx]
    mov     ax, 0x4
    push    ax
    push    word ptr [bp+colour]
    call    far ptr preRender_wheel_helper4
    add     sp, 0x14
    lea     ax, [bp+vertlines_arr+4]
    mov     word ptr [bp+var_4], ax
    mov     ax, word ptr [bp+vertlines_arr+2]
    mov     word ptr [bp+var_118], ax
    mov     word ptr [bp+var_11A], 0x0
    mov     word ptr [bp+var_110], 0x1
LAB_36c7_00bc:
    mov     bx, word ptr [bp+var_4]
    mov     ax, word ptr [bp+var_118]
    cmp     word ptr [bx+0x2], ax
    jge     LAB_36c7_00d7
    mov     ax, word ptr [bx+0x2]
    mov     word ptr [bp+var_118], ax
    mov     ax, word ptr [bp+var_110]
    mov     word ptr [bp+var_11A], ax
LAB_36c7_00d7:
    add     word ptr [bp+var_4], 0x4
    inc     word ptr [bp+var_110]
    cmp     word ptr [bp+var_110], 0x10
    jl      LAB_36c7_00bc
    mov     si, word ptr [bp+var_11A]
    mov     cl, 0x2
    shl     si, cl
    add     si, bp
    lea     ax, [si+0xfef2]
    mov     word ptr [bp+var_4], ax
    lea     ax, [si+0xff32]
    mov     word ptr [bp+var_114], ax
    lea     ax, [bp+var_4E]
    mov     word ptr [bp+var_6], ax
    lea     ax, [bp+var_A]
    mov     word ptr [bp+var_116], ax
    mov     ax, word ptr [bp+var_11A]
    mov     word ptr [bp+var_112], ax
    mov     word ptr [bp+var_110], 0x0
    jmp     LAB_36c7_0132
LAB_36c7_011c:
    add     word ptr [bp+var_4], 0x4
    add     word ptr [bp+var_114], 0x4
LAB_36c7_0125:
    add     word ptr [bp+var_6], 0x4
    sub     word ptr [bp+var_116], 0x4
    inc     word ptr [bp+var_110]
LAB_36c7_0132:
    cmp     word ptr [bp+var_110], 0x8
    jg      LAB_36c7_017e
    mov     bx, word ptr [bp+var_6]
    mov     si, word ptr [bp+var_4]
    mov     ax, word ptr [si]
    mov     word ptr [bx], ax
    mov     ax, word ptr [si+0x2]
    mov     word ptr [bx+0x2], ax
    mov     bx, word ptr [bp+var_116]
    mov     si, word ptr [bp+var_114]
    mov     ax, word ptr [si]
    mov     word ptr [bx], ax
    mov     ax, word ptr [si+0x2]
    mov     word ptr [bx+0x2], ax
    inc     word ptr [bp+var_112]
    cmp     word ptr [bp+var_112], 0x10
    jl      LAB_36c7_011c
    lea     ax, [bp+vertlines_arr]
    mov     word ptr [bp+var_4], ax
    lea     ax, [bp+var_CE]
    mov     word ptr [bp+var_114], ax
    mov     word ptr [bp+var_112], 0x0
    jmp     LAB_36c7_0125
    db 0x90
LAB_36c7_017e:
    lea     ax, [bp+var_4E]
    push    ax
    mov     ax, 0x12
    push    ax
    push    word ptr [bp+param_4]
    call    far ptr preRender_default_alt
    add     sp, 0x6
    mov     si, word ptr [bp+var_11A]
    mov     cl, 0x2
    shl     si, cl
    add     si, bp
    lea     ax, [si+0xfef2]
    mov     word ptr [bp+var_4], ax
    lea     ax, [si+0xff32]
    mov     word ptr [bp+var_114], ax
    lea     ax, [bp+var_4E]
    mov     word ptr [bp+var_6], ax
    lea     ax, [bp+var_A]
    mov     word ptr [bp+var_116], ax
    mov     ax, word ptr [bp+var_11A]
    mov     word ptr [bp+var_112], ax
    mov     word ptr [bp+var_110], 0x0
    jmp     LAB_36c7_01de
    db 0x90
LAB_36c7_01c8:
    sub     word ptr [bp+var_4], 0x4
    sub     word ptr [bp+var_114], 0x4
LAB_36c7_01d1:
    add     word ptr [bp+var_6], 0x4
    sub     word ptr [bp+var_116], 0x4
    inc     word ptr [bp+var_110]
LAB_36c7_01de:
    cmp     word ptr [bp+var_110], 0x9
    jge     LAB_36c7_0224
    mov     bx, word ptr [bp+var_6]
    mov     si, word ptr [bp+var_4]
    mov     ax, word ptr [si]
    mov     word ptr [bx], ax
    mov     ax, word ptr [si+0x2]
    mov     word ptr [bx+0x2], ax
    mov     bx, word ptr [bp+var_116]
    mov     si, word ptr [bp+var_114]
    mov     ax, word ptr [si]
    mov     word ptr [bx], ax
    mov     ax, word ptr [si+0x2]
    mov     word ptr [bx+0x2], ax
    dec     word ptr [bp+var_112]
    jns     LAB_36c7_01c8
    lea     ax, [bp+var_D2]
    mov     word ptr [bp+var_4], ax
    lea     ax, [bp+var_92]
    mov     word ptr [bp+var_114], ax
    mov     word ptr [bp+var_112], 0x10
    jmp     LAB_36c7_01d1
LAB_36c7_0224:
    lea     ax, [bp+var_4E]
    push    ax
    mov     ax, 0x12
    push    ax
    push    word ptr [bp+param_4]
    call    far ptr preRender_default_alt
    add     sp, 0x6
    lea     ax, [bp+var_CE]
    push    ax
    mov     ax, 0x10
    push    ax
    push    word ptr [bp+param_5]
    call    far ptr preRender_default_alt
    add     sp, 0x6
    pop     si
    mov     sp, bp
    pop     bp
    retf
preRender_wheel endp

seg022 ends
end
