; Generated by restunts-export.py (Ghidra)
.8086
.model medium

include seg018.inc

seg018 segment byte public use16 'STUNTSC'
    assume cs:seg018, es:nothing, ss:nothing, ds:dseg

    retf
    db 0x90

; void __cdecl16far kb_shift_checking1(void)
kb_shift_checking1_asm_ proc far
    mov     ax, 0x40
    mov     es, ax
    or      byte ptr es:[0x17], 0x20           ; 40h:17h = keyboard shift flags
    call    far ptr kb_checking
    retf
kb_shift_checking1_asm_ endp

; void __cdecl16far kb_shift_checking2(void)
kb_shift_checking2_asm_ proc far
    mov     ax, 0x40
    mov     es, ax
    and     byte ptr es:[0x17], 0xdf           ; 40h:17h = keyboard shift flags
    call    far ptr kb_checking
    retf
kb_shift_checking2_asm_ endp

seg018 ends
end
