; Generated by restunts-export.py (Ghidra)
.8086
.model medium

include seg033.inc

seg033 segment byte public use16 'STUNTSC'
    assume cs:seg033, es:nothing, ss:nothing, ds:dseg

; void __cdecl16far setup_mcgawnd1(void)
setup_mcgawnd1_asm_ proc far
    mov     ax, word ptr [mcgawndsprite]
    or      ax, word ptr [mcgawndsprite+2]
    jnz     LAB_3a95_002c
    mov     ax, 0xf
    push    ax
    mov     ax, 0xc8
    push    ax
    mov     ax, 0x140
    push    ax
    call    far ptr sprite_make_wnd
    add     sp, 0x6
    mov     word ptr [mcgawndsprite], ax
    mov     word ptr [mcgawndsprite+2], dx
LAB_3a95_002c:
    mov     ax, offset sprite2
; <REPLACE>
    mov     dx, seg seg012
; </REPLACE>
;    mov     dx, 0x2ea2
    push    dx
    push    ax
    call    far ptr sprite_set_1_from_argptr
    add     sp, 0x4
    les     bx, [mcgawndsprite]
    push    word ptr es:[bx+0x2]
    push    word ptr es:[bx]
    call    far ptr sprite_putimage
    add     sp, 0x4
    retf
setup_mcgawnd1_asm_ endp

; void __cdecl16far setup_mcgawnd2(void)
setup_mcgawnd2_asm_ proc far
    mov     ax, word ptr [mcgawndsprite]
    or      ax, word ptr [mcgawndsprite+2]
    jnz     LAB_3a95_0074
    mov     ax, 0xf
    push    ax
    mov     ax, 0xc8
    push    ax
    mov     ax, 0x140
    push    ax
    call    far ptr sprite_make_wnd
    add     sp, 0x6
    mov     word ptr [mcgawndsprite], ax
    mov     word ptr [mcgawndsprite+2], dx
LAB_3a95_0074:
    push    word ptr [mcgawndsprite+2]
    push    word ptr [mcgawndsprite]
    call    far ptr sprite_set_1_from_argptr
    add     sp, 0x4
    retf
setup_mcgawnd2_asm_ endp

seg033 ends
end
